import { Student, Mentor, AuditLog } from './types';

export const INITIAL_STUDENTS: Student[] = [
  {
    "id": "1",
    "regId": "45954860",
    "name": "Shreya Das",
    "email": "shreya.das1@example.com",
    "batch": "RB01_2026",
    "admissionDate": "2025-01-01",
    "daysWaiting": 0,
    "program": "Foundation Course",
    "mode": "Offline",
    "category": "Working",
    "performance": "Excellent",
    "activityStatus": "Inactive",
    "inactiveDays": 3,
    "contactNo": "9876564582",
    "assignedMentor": "Rajesh Koothrappali"
  },
  {
    "id": "2",
    "regId": "45954861",
    "name": "Diya Patel",
    "email": "diya.patel2@example.com",
    "batch": "RB01_2026",
    "admissionDate": "2025-01-01",
    "daysWaiting": 19,
    "program": "Foundation Course",
    "mode": "Online",
    "category": "Working",
    "performance": "Poor",
    "activityStatus": "Inactive",
    "inactiveDays": 30,
    "contactNo": "9876514166"
  },
  {
    "id": "3",
    "regId": "45954862",
    "name": "Shreya Yadav",
    "email": "shreya.yadav3@example.com",
    "batch": "RB01_2026",
    "admissionDate": "2025-01-01",
    "daysWaiting": 0,
    "program": "Foundation Course",
    "mode": "Offline",
    "category": "College",
    "performance": "Poor",
    "activityStatus": "Active",
    "inactiveDays": 3,
    "contactNo": "9876510262",
    "assignedMentor": "Sanjay Dutt"
  },
  {
    "id": "4",
    "regId": "45954863",
    "name": "Ayan Gupta",
    "email": "ayan.gupta4@example.com",
    "batch": "RB01_2026",
    "admissionDate": "2025-01-01",
    "daysWaiting": 28,
    "program": "Foundation Course",
    "mode": "Offline",
    "category": "College",
    "performance": "Average",
    "activityStatus": "Inactive",
    "inactiveDays": 17,
    "contactNo": "9876547541"
  },
  {
    "id": "5",
    "regId": "45954864",
    "name": "Anya Das",
    "email": "anya.das5@example.com",
    "batch": "RB01_2026",
    "admissionDate": "2025-01-01",
    "daysWaiting": 1,
    "program": "Foundation Course",
    "mode": "Offline",
    "category": "Full time",
    "performance": "Very Good",
    "activityStatus": "Active",
    "inactiveDays": 10,
    "contactNo": "9876583885"
  },
  {
    "id": "6",
    "regId": "45954865",
    "name": "Aarav Chopra",
    "email": "aarav.chopra6@example.com",
    "batch": "RB01_2026",
    "admissionDate": "2025-01-01",
    "daysWaiting": 0,
    "program": "Foundation Course",
    "mode": "Online",
    "category": "College",
    "performance": "Average",
    "activityStatus": "Inactive",
    "inactiveDays": 0,
    "contactNo": "9876588896",
    "assignedMentor": "Sanjay Dutt"
  },
  {
    "id": "7",
    "regId": "45954866",
    "name": "Ayan Reddy",
    "email": "ayan.reddy7@example.com",
    "batch": "RB01_2026",
    "admissionDate": "2025-01-01",
    "daysWaiting": 12,
    "program": "Foundation Course",
    "mode": "Offline",
    "category": "Working",
    "performance": "Good",
    "activityStatus": "Active",
    "inactiveDays": 12,
    "contactNo": "9876571197"
  },
  {
    "id": "8",
    "regId": "45954867",
    "name": "Pari Mehta",
    "email": "pari.mehta8@example.com",
    "batch": "RB01_2026",
    "admissionDate": "2025-01-01",
    "daysWaiting": 0,
    "program": "Foundation Course",
    "mode": "Online",
    "category": "College",
    "performance": "Very Good",
    "activityStatus": "Inactive",
    "inactiveDays": 0,
    "contactNo": "9876543770",
    "assignedMentor": "Meera Reddy"
  },
  {
    "id": "9",
    "regId": "45954868",
    "name": "Ayan Malhotra",
    "email": "ayan.malhotra9@example.com",
    "batch": "RB01_2026",
    "admissionDate": "2025-01-01",
    "daysWaiting": 0,
    "program": "Foundation Course",
    "mode": "Online",
    "category": "Working",
    "performance": "Good",
    "activityStatus": "Inactive",
    "inactiveDays": 27,
    "contactNo": "9876548178",
    "assignedMentor": "Meera Reddy"
  },
  {
    "id": "10",
    "regId": "45954869",
    "name": "Aarav Rao",
    "email": "aarav.rao10@example.com",
    "batch": "RB01_2026",
    "admissionDate": "2025-01-01",
    "daysWaiting": 7,
    "program": "Foundation Course",
    "mode": "Online",
    "category": "College",
    "performance": "Poor",
    "activityStatus": "Active",
    "inactiveDays": 26,
    "contactNo": "9876531779"
  },
  {
    "id": "11",
    "regId": "45954870",
    "name": "Amit Patel",
    "email": "amit.patel11@example.com",
    "batch": "RB01_2026",
    "admissionDate": "2025-01-01",
    "daysWaiting": 0,
    "program": "Foundation Course",
    "mode": "Online",
    "category": "Working",
    "performance": "Average",
    "activityStatus": "Inactive",
    "inactiveDays": 8,
    "contactNo": "9876533209",
    "assignedMentor": "Rajesh Koothrappali"
  },
  {
    "id": "12",
    "regId": "45954871",
    "name": "Vivaan Kumar",
    "email": "vivaan.kumar12@example.com",
    "batch": "RB01_2026",
    "admissionDate": "2025-01-01",
    "daysWaiting": 27,
    "program": "Foundation Course",
    "mode": "Online",
    "category": "Working",
    "performance": "Good",
    "activityStatus": "Inactive",
    "inactiveDays": 28,
    "contactNo": "9876512076"
  },
  {
    "id": "13",
    "regId": "45954872",
    "name": "Reyansh Iyer",
    "email": "reyansh.iyer13@example.com",
    "batch": "RB01_2026",
    "admissionDate": "2025-01-01",
    "daysWaiting": 2,
    "program": "Foundation Course",
    "mode": "Online",
    "category": "Full time",
    "performance": "Poor",
    "activityStatus": "Active",
    "inactiveDays": 5,
    "contactNo": "9876570306"
  },
  {
    "id": "14",
    "regId": "45954873",
    "name": "Vikram Bose",
    "email": "vikram.bose14@example.com",
    "batch": "RB01_2026",
    "admissionDate": "2025-01-01",
    "daysWaiting": 0,
    "program": "Foundation Course",
    "mode": "Online",
    "category": "College",
    "performance": "Very Good",
    "activityStatus": "Inactive",
    "inactiveDays": 7,
    "contactNo": "9876545963",
    "assignedMentor": "Arjun Mehta"
  },
  {
    "id": "15",
    "regId": "45954874",
    "name": "Sai Das",
    "email": "sai.das15@example.com",
    "batch": "RB02_2026",
    "admissionDate": "2025-01-01",
    "daysWaiting": 23,
    "program": "Foundation Course",
    "mode": "Online",
    "category": "Full time",
    "performance": "Excellent",
    "activityStatus": "Inactive",
    "inactiveDays": 25,
    "contactNo": "9876516614"
  },
  {
    "id": "16",
    "regId": "45954875",
    "name": "Rahul Malhotra",
    "email": "rahul.malhotra16@example.com",
    "batch": "RB02_2026",
    "admissionDate": "2025-01-01",
    "daysWaiting": 0,
    "program": "Foundation Course",
    "mode": "Online",
    "category": "College",
    "performance": "Very Good",
    "activityStatus": "Inactive",
    "inactiveDays": 3,
    "contactNo": "9876595434",
    "assignedMentor": "Arjun Mehta"
  },
  {
    "id": "17",
    "regId": "45954876",
    "name": "Ayan Reddy",
    "email": "ayan.reddy17@example.com",
    "batch": "RB02_2026",
    "admissionDate": "2025-01-01",
    "daysWaiting": 0,
    "program": "Foundation Course",
    "mode": "Offline",
    "category": "Working",
    "performance": "Very Good",
    "activityStatus": "Active",
    "inactiveDays": 14,
    "contactNo": "9876516949",
    "assignedMentor": "Arjun Mehta"
  },
  {
    "id": "18",
    "regId": "45954877",
    "name": "Ananya Mishra",
    "email": "ananya.mishra18@example.com",
    "batch": "RB02_2026",
    "admissionDate": "2025-01-01",
    "daysWaiting": 11,
    "program": "Foundation Course",
    "mode": "Online",
    "category": "Working",
    "performance": "Excellent",
    "activityStatus": "Active",
    "inactiveDays": 27,
    "contactNo": "9876544745"
  },
  {
    "id": "19",
    "regId": "45954878",
    "name": "Sneha Singh",
    "email": "sneha.singh19@example.com",
    "batch": "RB02_2026",
    "admissionDate": "2025-01-01",
    "daysWaiting": 29,
    "program": "Foundation Course",
    "mode": "Online",
    "category": "Full time",
    "performance": "Very Good",
    "activityStatus": "Inactive",
    "inactiveDays": 27,
    "contactNo": "9876544631"
  },
  {
    "id": "20",
    "regId": "45954879",
    "name": "Shreya Malhotra",
    "email": "shreya.malhotra20@example.com",
    "batch": "RB02_2026",
    "admissionDate": "2025-01-01",
    "daysWaiting": 0,
    "program": "Foundation Course",
    "mode": "Offline",
    "category": "Full time",
    "performance": "Poor",
    "activityStatus": "Inactive",
    "inactiveDays": 26,
    "contactNo": "9876591191",
    "assignedMentor": "Meera Reddy"
  },
  {
    "id": "21",
    "regId": "45954880",
    "name": "Anya Chopra",
    "email": "anya.chopra21@example.com",
    "batch": "RB02_2026",
    "admissionDate": "2025-01-01",
    "daysWaiting": 0,
    "program": "Foundation Course",
    "mode": "Offline",
    "category": "Working",
    "performance": "Excellent",
    "activityStatus": "Inactive",
    "inactiveDays": 12,
    "contactNo": "9876585059",
    "assignedMentor": "Meera Reddy"
  },
  {
    "id": "22",
    "regId": "45954881",
    "name": "Vihaan Chatterjee",
    "email": "vihaan.chatterjee22@example.com",
    "batch": "RB02_2026",
    "admissionDate": "2025-01-01",
    "daysWaiting": 0,
    "program": "Foundation Course",
    "mode": "Offline",
    "category": "Full time",
    "performance": "Average",
    "activityStatus": "Inactive",
    "inactiveDays": 16,
    "contactNo": "9876550311",
    "assignedMentor": "Arjun Mehta"
  },
  {
    "id": "23",
    "regId": "45954882",
    "name": "Ananya Bose",
    "email": "ananya.bose23@example.com",
    "batch": "RB02_2026",
    "admissionDate": "2025-01-01",
    "daysWaiting": 0,
    "program": "Foundation Course",
    "mode": "Online",
    "category": "Working",
    "performance": "Very Good",
    "activityStatus": "Inactive",
    "inactiveDays": 23,
    "contactNo": "9876568618",
    "assignedMentor": "Sanjay Dutt"
  },
  {
    "id": "24",
    "regId": "45954883",
    "name": "Aarav Chatterjee",
    "email": "aarav.chatterjee24@example.com",
    "batch": "RB02_2026",
    "admissionDate": "2025-01-01",
    "daysWaiting": 0,
    "program": "Foundation Course",
    "mode": "Offline",
    "category": "Working",
    "performance": "Excellent",
    "activityStatus": "Active",
    "inactiveDays": 12,
    "contactNo": "9876564878",
    "assignedMentor": "Kavita Rao"
  },
  {
    "id": "25",
    "regId": "45954884",
    "name": "Ishaan Mehta",
    "email": "ishaan.mehta25@example.com",
    "batch": "RB02_2026",
    "admissionDate": "2025-01-01",
    "daysWaiting": 30,
    "program": "Foundation Course",
    "mode": "Online",
    "category": "Working",
    "performance": "Poor",
    "activityStatus": "Inactive",
    "inactiveDays": 14,
    "contactNo": "9876552154"
  },
  {
    "id": "26",
    "regId": "45954885",
    "name": "Ishaan Reddy",
    "email": "ishaan.reddy26@example.com",
    "batch": "RB02_2026",
    "admissionDate": "2025-01-01",
    "daysWaiting": 8,
    "program": "Foundation Course",
    "mode": "Online",
    "category": "College",
    "performance": "Poor",
    "activityStatus": "Inactive",
    "inactiveDays": 24,
    "contactNo": "9876564150"
  },
  {
    "id": "27",
    "regId": "45954886",
    "name": "Rahul Saxena",
    "email": "rahul.saxena27@example.com",
    "batch": "RB02_2026",
    "admissionDate": "2025-01-01",
    "daysWaiting": 8,
    "program": "Foundation Course",
    "mode": "Offline",
    "category": "Full time",
    "performance": "Poor",
    "activityStatus": "Inactive",
    "inactiveDays": 6,
    "contactNo": "9876534725"
  },
  {
    "id": "28",
    "regId": "45954887",
    "name": "Aarav Jain",
    "email": "aarav.jain28@example.com",
    "batch": "RB02_2026",
    "admissionDate": "2025-01-01",
    "daysWaiting": 7,
    "program": "Foundation Course",
    "mode": "Offline",
    "category": "College",
    "performance": "Poor",
    "activityStatus": "Inactive",
    "inactiveDays": 6,
    "contactNo": "9876566404"
  },
  {
    "id": "29",
    "regId": "45954888",
    "name": "Shreya Singh",
    "email": "shreya.singh29@example.com",
    "batch": "RB03_2026",
    "admissionDate": "2025-01-01",
    "daysWaiting": 14,
    "program": "Foundation Course",
    "mode": "Online",
    "category": "Full time",
    "performance": "Very Good",
    "activityStatus": "Active",
    "inactiveDays": 2,
    "contactNo": "9876585777"
  },
  {
    "id": "30",
    "regId": "45954889",
    "name": "Saanvi Iyer",
    "email": "saanvi.iyer30@example.com",
    "batch": "RB03_2026",
    "admissionDate": "2025-01-01",
    "daysWaiting": 15,
    "program": "Foundation Course",
    "mode": "Online",
    "category": "College",
    "performance": "Very Good",
    "activityStatus": "Inactive",
    "inactiveDays": 2,
    "contactNo": "9876551343"
  },
  {
    "id": "31",
    "regId": "45954890",
    "name": "Pooja Chopra",
    "email": "pooja.chopra31@example.com",
    "batch": "RB03_2026",
    "admissionDate": "2025-01-01",
    "daysWaiting": 17,
    "program": "Foundation Course",
    "mode": "Offline",
    "category": "College",
    "performance": "Poor",
    "activityStatus": "Inactive",
    "inactiveDays": 0,
    "contactNo": "9876555482"
  },
  {
    "id": "32",
    "regId": "45954891",
    "name": "Amit Mehta",
    "email": "amit.mehta32@example.com",
    "batch": "RB03_2026",
    "admissionDate": "2025-01-01",
    "daysWaiting": 16,
    "program": "Foundation Course",
    "mode": "Offline",
    "category": "Full time",
    "performance": "Excellent",
    "activityStatus": "Inactive",
    "inactiveDays": 26,
    "contactNo": "9876524638"
  },
  {
    "id": "33",
    "regId": "45954892",
    "name": "Krishna Verma",
    "email": "krishna.verma33@example.com",
    "batch": "RB03_2026",
    "admissionDate": "2025-01-01",
    "daysWaiting": 1,
    "program": "Foundation Course",
    "mode": "Offline",
    "category": "Working",
    "performance": "Average",
    "activityStatus": "Active",
    "inactiveDays": 6,
    "contactNo": "9876576186"
  },
  {
    "id": "34",
    "regId": "45954893",
    "name": "Krishna Gupta",
    "email": "krishna.gupta34@example.com",
    "batch": "RB03_2026",
    "admissionDate": "2025-01-01",
    "daysWaiting": 0,
    "program": "Foundation Course",
    "mode": "Offline",
    "category": "College",
    "performance": "Average",
    "activityStatus": "Inactive",
    "inactiveDays": 17,
    "contactNo": "9876518012",
    "assignedMentor": "Meera Reddy"
  },
  {
    "id": "35",
    "regId": "45954894",
    "name": "Navya Mehta",
    "email": "navya.mehta35@example.com",
    "batch": "RB03_2026",
    "admissionDate": "2025-01-01",
    "daysWaiting": 29,
    "program": "Foundation Course",
    "mode": "Offline",
    "category": "Working",
    "performance": "Very Good",
    "activityStatus": "Inactive",
    "inactiveDays": 11,
    "contactNo": "9876532673"
  },
  {
    "id": "36",
    "regId": "45954895",
    "name": "Amit Jain",
    "email": "amit.jain36@example.com",
    "batch": "RB03_2026",
    "admissionDate": "2025-01-01",
    "daysWaiting": 20,
    "program": "Foundation Course",
    "mode": "Online",
    "category": "Working",
    "performance": "Excellent",
    "activityStatus": "Inactive",
    "inactiveDays": 1,
    "contactNo": "9876543442"
  },
  {
    "id": "37",
    "regId": "45954896",
    "name": "Riya Mehta",
    "email": "riya.mehta37@example.com",
    "batch": "RB03_2026",
    "admissionDate": "2025-01-01",
    "daysWaiting": 0,
    "program": "Foundation Course",
    "mode": "Offline",
    "category": "Working",
    "performance": "Average",
    "activityStatus": "Inactive",
    "inactiveDays": 1,
    "contactNo": "9876570201",
    "assignedMentor": "Meera Reddy"
  },
  {
    "id": "38",
    "regId": "45954897",
    "name": "Vivaan Malhotra",
    "email": "vivaan.malhotra38@example.com",
    "batch": "RB03_2026",
    "admissionDate": "2025-01-01",
    "daysWaiting": 0,
    "program": "Foundation Course",
    "mode": "Offline",
    "category": "Full time",
    "performance": "Poor",
    "activityStatus": "Inactive",
    "inactiveDays": 21,
    "contactNo": "9876557832",
    "assignedMentor": "Arjun Mehta"
  },
  {
    "id": "39",
    "regId": "45954898",
    "name": "Amit Gupta",
    "email": "amit.gupta39@example.com",
    "batch": "RB03_2026",
    "admissionDate": "2025-01-01",
    "daysWaiting": 30,
    "program": "Foundation Course",
    "mode": "Online",
    "category": "Full time",
    "performance": "Very Good",
    "activityStatus": "Active",
    "inactiveDays": 5,
    "contactNo": "9876528516"
  },
  {
    "id": "40",
    "regId": "45954899",
    "name": "Aarav Nair",
    "email": "aarav.nair40@example.com",
    "batch": "RB04_2026",
    "admissionDate": "2025-01-01",
    "daysWaiting": 0,
    "program": "Foundation Course",
    "mode": "Offline",
    "category": "Full time",
    "performance": "Excellent",
    "activityStatus": "Inactive",
    "inactiveDays": 7,
    "contactNo": "9876561159",
    "assignedMentor": "Arjun Mehta"
  },
  {
    "id": "41",
    "regId": "45954900",
    "name": "Ananya Yadav",
    "email": "ananya.yadav41@example.com",
    "batch": "RB04_2026",
    "admissionDate": "2025-01-01",
    "daysWaiting": 13,
    "program": "Foundation Course",
    "mode": "Online",
    "category": "Working",
    "performance": "Average",
    "activityStatus": "Active",
    "inactiveDays": 6,
    "contactNo": "9876580610"
  },
  {
    "id": "42",
    "regId": "45954901",
    "name": "Pooja Singh",
    "email": "pooja.singh42@example.com",
    "batch": "RB04_2026",
    "admissionDate": "2025-01-01",
    "daysWaiting": 21,
    "program": "Foundation Course",
    "mode": "Online",
    "category": "Working",
    "performance": "Good",
    "activityStatus": "Active",
    "inactiveDays": 27,
    "contactNo": "9876592294"
  },
  {
    "id": "43",
    "regId": "45954902",
    "name": "Sai Chatterjee",
    "email": "sai.chatterjee43@example.com",
    "batch": "RB04_2026",
    "admissionDate": "2025-01-01",
    "daysWaiting": 14,
    "program": "Foundation Course",
    "mode": "Online",
    "category": "College",
    "performance": "Excellent",
    "activityStatus": "Inactive",
    "inactiveDays": 20,
    "contactNo": "9876544408"
  },
  {
    "id": "44",
    "regId": "45954903",
    "name": "Pooja Malhotra",
    "email": "pooja.malhotra44@example.com",
    "batch": "RB04_2026",
    "admissionDate": "2025-01-01",
    "daysWaiting": 0,
    "program": "Foundation Course",
    "mode": "Online",
    "category": "Full time",
    "performance": "Very Good",
    "activityStatus": "Inactive",
    "inactiveDays": 4,
    "contactNo": "9876517814",
    "assignedMentor": "Rajesh Koothrappali"
  },
  {
    "id": "45",
    "regId": "45954904",
    "name": "Krishna Nair",
    "email": "krishna.nair45@example.com",
    "batch": "RB04_2026",
    "admissionDate": "2025-01-01",
    "daysWaiting": 0,
    "program": "Foundation Course",
    "mode": "Offline",
    "category": "College",
    "performance": "Good",
    "activityStatus": "Active",
    "inactiveDays": 18,
    "contactNo": "9876556910",
    "assignedMentor": "Kavita Rao"
  },
  {
    "id": "46",
    "regId": "45954905",
    "name": "Vihaan Reddy",
    "email": "vihaan.reddy46@example.com",
    "batch": "RB04_2026",
    "admissionDate": "2025-01-01",
    "daysWaiting": 26,
    "program": "Foundation Course",
    "mode": "Online",
    "category": "Full time",
    "performance": "Very Good",
    "activityStatus": "Inactive",
    "inactiveDays": 21,
    "contactNo": "9876511730"
  },
  {
    "id": "47",
    "regId": "45954906",
    "name": "Ayan Mishra",
    "email": "ayan.mishra47@example.com",
    "batch": "RB04_2026",
    "admissionDate": "2025-01-01",
    "daysWaiting": 13,
    "program": "Foundation Course",
    "mode": "Offline",
    "category": "College",
    "performance": "Poor",
    "activityStatus": "Inactive",
    "inactiveDays": 14,
    "contactNo": "9876521099"
  },
  {
    "id": "48",
    "regId": "45954907",
    "name": "Aarav Patel",
    "email": "aarav.patel48@example.com",
    "batch": "RB04_2026",
    "admissionDate": "2025-01-01",
    "daysWaiting": 15,
    "program": "Foundation Course",
    "mode": "Offline",
    "category": "Working",
    "performance": "Poor",
    "activityStatus": "Active",
    "inactiveDays": 17,
    "contactNo": "9876591959"
  },
  {
    "id": "49",
    "regId": "45954908",
    "name": "Rahul Patel",
    "email": "rahul.patel49@example.com",
    "batch": "RB04_2026",
    "admissionDate": "2025-01-01",
    "daysWaiting": 0,
    "program": "Foundation Course",
    "mode": "Offline",
    "category": "Full time",
    "performance": "Very Good",
    "activityStatus": "Active",
    "inactiveDays": 2,
    "contactNo": "9876518740",
    "assignedMentor": "Kavita Rao"
  },
  {
    "id": "50",
    "regId": "45954909",
    "name": "Ayan Gupta",
    "email": "ayan.gupta50@example.com",
    "batch": "RB04_2026",
    "admissionDate": "2025-01-01",
    "daysWaiting": 29,
    "program": "Foundation Course",
    "mode": "Online",
    "category": "Working",
    "performance": "Excellent",
    "activityStatus": "Active",
    "inactiveDays": 10,
    "contactNo": "9876562856"
  },
  {
    "id": "51",
    "regId": "45954910",
    "name": "Sneha Nair",
    "email": "sneha.nair51@example.com",
    "batch": "RB04_2026",
    "admissionDate": "2025-01-01",
    "daysWaiting": 0,
    "program": "Foundation Course",
    "mode": "Online",
    "category": "Working",
    "performance": "Good",
    "activityStatus": "Active",
    "inactiveDays": 5,
    "contactNo": "9876562847",
    "assignedMentor": "Arjun Mehta"
  },
  {
    "id": "52",
    "regId": "45954911",
    "name": "Arjun Malhotra",
    "email": "arjun.malhotra52@example.com",
    "batch": "RB04_2026",
    "admissionDate": "2025-01-01",
    "daysWaiting": 0,
    "program": "Foundation Course",
    "mode": "Offline",
    "category": "Working",
    "performance": "Poor",
    "activityStatus": "Inactive",
    "inactiveDays": 18,
    "contactNo": "9876557059",
    "assignedMentor": "Kavita Rao"
  },
  {
    "id": "53",
    "regId": "45954912",
    "name": "Amit Nair",
    "email": "amit.nair53@example.com",
    "batch": "RB04_2026",
    "admissionDate": "2025-01-01",
    "daysWaiting": 0,
    "program": "Foundation Course",
    "mode": "Online",
    "category": "Working",
    "performance": "Average",
    "activityStatus": "Active",
    "inactiveDays": 4,
    "contactNo": "9876537341",
    "assignedMentor": "Sanjay Dutt"
  },
  {
    "id": "54",
    "regId": "45954913",
    "name": "Navya Rao",
    "email": "navya.rao54@example.com",
    "batch": "RB05_2026",
    "admissionDate": "2025-01-01",
    "daysWaiting": 0,
    "program": "Foundation Course",
    "mode": "Offline",
    "category": "Working",
    "performance": "Average",
    "activityStatus": "Active",
    "inactiveDays": 5,
    "contactNo": "9876549013",
    "assignedMentor": "Sanjay Dutt"
  },
  {
    "id": "55",
    "regId": "45954914",
    "name": "Ishaan Reddy",
    "email": "ishaan.reddy55@example.com",
    "batch": "RB05_2026",
    "admissionDate": "2025-01-01",
    "daysWaiting": 0,
    "program": "Foundation Course",
    "mode": "Online",
    "category": "Working",
    "performance": "Average",
    "activityStatus": "Active",
    "inactiveDays": 25,
    "contactNo": "9876531692",
    "assignedMentor": "Arjun Mehta"
  },
  {
    "id": "56",
    "regId": "45954915",
    "name": "Anika Das",
    "email": "anika.das56@example.com",
    "batch": "RB05_2026",
    "admissionDate": "2025-01-01",
    "daysWaiting": 0,
    "program": "Foundation Course",
    "mode": "Online",
    "category": "Working",
    "performance": "Excellent",
    "activityStatus": "Active",
    "inactiveDays": 10,
    "contactNo": "9876554072",
    "assignedMentor": "Meera Reddy"
  },
  {
    "id": "57",
    "regId": "45954916",
    "name": "Aditya Verma",
    "email": "aditya.verma57@example.com",
    "batch": "RB05_2026",
    "admissionDate": "2025-01-01",
    "daysWaiting": 22,
    "program": "Foundation Course",
    "mode": "Offline",
    "category": "Working",
    "performance": "Average",
    "activityStatus": "Active",
    "inactiveDays": 14,
    "contactNo": "9876583750"
  },
  {
    "id": "58",
    "regId": "45954917",
    "name": "Vihaan Iyer",
    "email": "vihaan.iyer58@example.com",
    "batch": "RB05_2026",
    "admissionDate": "2025-01-01",
    "daysWaiting": 0,
    "program": "Foundation Course",
    "mode": "Offline",
    "category": "Full time",
    "performance": "Very Good",
    "activityStatus": "Inactive",
    "inactiveDays": 18,
    "contactNo": "9876512398",
    "assignedMentor": "Meera Reddy"
  },
  {
    "id": "59",
    "regId": "45954918",
    "name": "Saanvi Patel",
    "email": "saanvi.patel59@example.com",
    "batch": "RB05_2026",
    "admissionDate": "2025-01-01",
    "daysWaiting": 0,
    "program": "Foundation Course",
    "mode": "Online",
    "category": "College",
    "performance": "Excellent",
    "activityStatus": "Inactive",
    "inactiveDays": 1,
    "contactNo": "9876516088",
    "assignedMentor": "Meera Reddy"
  },
  {
    "id": "60",
    "regId": "45954919",
    "name": "Aditya Jain",
    "email": "aditya.jain60@example.com",
    "batch": "RB05_2026",
    "admissionDate": "2025-01-01",
    "daysWaiting": 1,
    "program": "Foundation Course",
    "mode": "Offline",
    "category": "College",
    "performance": "Very Good",
    "activityStatus": "Inactive",
    "inactiveDays": 0,
    "contactNo": "9876580051"
  },
  {
    "id": "61",
    "regId": "45954920",
    "name": "Vikram Jain",
    "email": "vikram.jain61@example.com",
    "batch": "RB05_2026",
    "admissionDate": "2025-01-01",
    "daysWaiting": 2,
    "program": "Foundation Course",
    "mode": "Online",
    "category": "Working",
    "performance": "Poor",
    "activityStatus": "Active",
    "inactiveDays": 29,
    "contactNo": "9876531909"
  },
  {
    "id": "62",
    "regId": "45954921",
    "name": "Sai Jain",
    "email": "sai.jain62@example.com",
    "batch": "RB05_2026",
    "admissionDate": "2025-01-01",
    "daysWaiting": 0,
    "program": "Foundation Course",
    "mode": "Offline",
    "category": "Working",
    "performance": "Poor",
    "activityStatus": "Inactive",
    "inactiveDays": 25,
    "contactNo": "9876569921",
    "assignedMentor": "Arjun Mehta"
  },
  {
    "id": "63",
    "regId": "45954922",
    "name": "Pari Gupta",
    "email": "pari.gupta63@example.com",
    "batch": "RB05_2026",
    "admissionDate": "2025-01-01",
    "daysWaiting": 0,
    "program": "Foundation Course",
    "mode": "Online",
    "category": "College",
    "performance": "Average",
    "activityStatus": "Active",
    "inactiveDays": 18,
    "contactNo": "9876548042",
    "assignedMentor": "Kavita Rao"
  },
  {
    "id": "64",
    "regId": "45954923",
    "name": "Navya Bose",
    "email": "navya.bose64@example.com",
    "batch": "RB05_2026",
    "admissionDate": "2025-01-01",
    "daysWaiting": 22,
    "program": "Foundation Course",
    "mode": "Online",
    "category": "College",
    "performance": "Excellent",
    "activityStatus": "Inactive",
    "inactiveDays": 16,
    "contactNo": "9876563576"
  },
  {
    "id": "65",
    "regId": "45954924",
    "name": "Reyansh Malhotra",
    "email": "reyansh.malhotra65@example.com",
    "batch": "RB06_2026",
    "admissionDate": "2025-01-01",
    "daysWaiting": 0,
    "program": "Foundation Course",
    "mode": "Offline",
    "category": "Full time",
    "performance": "Good",
    "activityStatus": "Active",
    "inactiveDays": 25,
    "contactNo": "9876595334",
    "assignedMentor": "Sanjay Dutt"
  },
  {
    "id": "66",
    "regId": "45954925",
    "name": "Riya Mishra",
    "email": "riya.mishra66@example.com",
    "batch": "RB06_2026",
    "admissionDate": "2025-01-01",
    "daysWaiting": 0,
    "program": "Foundation Course",
    "mode": "Offline",
    "category": "College",
    "performance": "Good",
    "activityStatus": "Inactive",
    "inactiveDays": 7,
    "contactNo": "9876565288",
    "assignedMentor": "Arjun Mehta"
  },
  {
    "id": "67",
    "regId": "45954926",
    "name": "Anya Kumar",
    "email": "anya.kumar67@example.com",
    "batch": "RB06_2026",
    "admissionDate": "2025-01-01",
    "daysWaiting": 0,
    "program": "Foundation Course",
    "mode": "Online",
    "category": "Full time",
    "performance": "Excellent",
    "activityStatus": "Active",
    "inactiveDays": 22,
    "contactNo": "9876525675",
    "assignedMentor": "Rajesh Koothrappali"
  },
  {
    "id": "68",
    "regId": "45954927",
    "name": "Sai Patel",
    "email": "sai.patel68@example.com",
    "batch": "RB06_2026",
    "admissionDate": "2025-01-01",
    "daysWaiting": 0,
    "program": "Foundation Course",
    "mode": "Online",
    "category": "Full time",
    "performance": "Average",
    "activityStatus": "Active",
    "inactiveDays": 10,
    "contactNo": "9876595675",
    "assignedMentor": "Sanjay Dutt"
  },
  {
    "id": "69",
    "regId": "45954928",
    "name": "Neha Singh",
    "email": "neha.singh69@example.com",
    "batch": "RB06_2026",
    "admissionDate": "2025-01-01",
    "daysWaiting": 0,
    "program": "Foundation Course",
    "mode": "Online",
    "category": "Full time",
    "performance": "Excellent",
    "activityStatus": "Active",
    "inactiveDays": 18,
    "contactNo": "9876521295",
    "assignedMentor": "Arjun Mehta"
  },
  {
    "id": "70",
    "regId": "45954929",
    "name": "Diya Jain",
    "email": "diya.jain70@example.com",
    "batch": "RB06_2026",
    "admissionDate": "2025-01-01",
    "daysWaiting": 20,
    "program": "Foundation Course",
    "mode": "Offline",
    "category": "Working",
    "performance": "Excellent",
    "activityStatus": "Active",
    "inactiveDays": 21,
    "contactNo": "9876517715"
  },
  {
    "id": "71",
    "regId": "45954930",
    "name": "Sneha Das",
    "email": "sneha.das71@example.com",
    "batch": "RB06_2026",
    "admissionDate": "2025-01-01",
    "daysWaiting": 23,
    "program": "Foundation Course",
    "mode": "Online",
    "category": "Full time",
    "performance": "Very Good",
    "activityStatus": "Active",
    "inactiveDays": 20,
    "contactNo": "9876552655"
  },
  {
    "id": "72",
    "regId": "45954931",
    "name": "Neha Das",
    "email": "neha.das72@example.com",
    "batch": "RB06_2026",
    "admissionDate": "2025-01-01",
    "daysWaiting": 0,
    "program": "Foundation Course",
    "mode": "Offline",
    "category": "College",
    "performance": "Poor",
    "activityStatus": "Inactive",
    "inactiveDays": 23,
    "contactNo": "9876521880",
    "assignedMentor": "Rajesh Koothrappali"
  },
  {
    "id": "73",
    "regId": "45954932",
    "name": "Navya Gupta",
    "email": "navya.gupta73@example.com",
    "batch": "RB06_2026",
    "admissionDate": "2025-01-01",
    "daysWaiting": 0,
    "program": "Foundation Course",
    "mode": "Offline",
    "category": "College",
    "performance": "Excellent",
    "activityStatus": "Inactive",
    "inactiveDays": 3,
    "contactNo": "9876582747",
    "assignedMentor": "Meera Reddy"
  },
  {
    "id": "74",
    "regId": "45954933",
    "name": "Sai Gupta",
    "email": "sai.gupta74@example.com",
    "batch": "RB06_2026",
    "admissionDate": "2025-01-01",
    "daysWaiting": 0,
    "program": "Foundation Course",
    "mode": "Offline",
    "category": "Working",
    "performance": "Good",
    "activityStatus": "Inactive",
    "inactiveDays": 23,
    "contactNo": "9876514367",
    "assignedMentor": "Rajesh Koothrappali"
  },
  {
    "id": "75",
    "regId": "45954934",
    "name": "Pari Reddy",
    "email": "pari.reddy75@example.com",
    "batch": "RB06_2026",
    "admissionDate": "2025-01-01",
    "daysWaiting": 2,
    "program": "Foundation Course",
    "mode": "Online",
    "category": "College",
    "performance": "Very Good",
    "activityStatus": "Inactive",
    "inactiveDays": 25,
    "contactNo": "9876571329"
  },
  {
    "id": "76",
    "regId": "45954935",
    "name": "Neha Singh",
    "email": "neha.singh76@example.com",
    "batch": "RB06_2026",
    "admissionDate": "2025-01-01",
    "daysWaiting": 4,
    "program": "Foundation Course",
    "mode": "Offline",
    "category": "Full time",
    "performance": "Excellent",
    "activityStatus": "Active",
    "inactiveDays": 22,
    "contactNo": "9876597937"
  },
  {
    "id": "77",
    "regId": "45954936",
    "name": "Rahul Reddy",
    "email": "rahul.reddy77@example.com",
    "batch": "RB06_2026",
    "admissionDate": "2025-01-01",
    "daysWaiting": 11,
    "program": "Foundation Course",
    "mode": "Offline",
    "category": "College",
    "performance": "Good",
    "activityStatus": "Inactive",
    "inactiveDays": 0,
    "contactNo": "9876516104"
  },
  {
    "id": "78",
    "regId": "45954937",
    "name": "Krishna Malhotra",
    "email": "krishna.malhotra78@example.com",
    "batch": "November 2025",
    "admissionDate": "2025-01-01",
    "daysWaiting": 0,
    "program": "Lakshya",
    "mode": "Online",
    "category": "College",
    "performance": "Good",
    "activityStatus": "Active",
    "inactiveDays": 29,
    "contactNo": "9876513772",
    "assignedMentor": "Kavita Rao"
  },
  {
    "id": "79",
    "regId": "45954938",
    "name": "Ananya Chopra",
    "email": "ananya.chopra79@example.com",
    "batch": "November 2025",
    "admissionDate": "2025-01-01",
    "daysWaiting": 30,
    "program": "Lakshya",
    "mode": "Online",
    "category": "College",
    "performance": "Excellent",
    "activityStatus": "Active",
    "inactiveDays": 9,
    "contactNo": "9876575764"
  },
  {
    "id": "80",
    "regId": "45954939",
    "name": "Pooja Das",
    "email": "pooja.das80@example.com",
    "batch": "November 2025",
    "admissionDate": "2025-01-01",
    "daysWaiting": 0,
    "program": "Lakshya",
    "mode": "Offline",
    "category": "Working",
    "performance": "Excellent",
    "activityStatus": "Active",
    "inactiveDays": 0,
    "contactNo": "9876535732",
    "assignedMentor": "Arjun Mehta"
  },
  {
    "id": "81",
    "regId": "45954940",
    "name": "Anya Mehta",
    "email": "anya.mehta81@example.com",
    "batch": "November 2025",
    "admissionDate": "2025-01-01",
    "daysWaiting": 24,
    "program": "Lakshya",
    "mode": "Offline",
    "category": "Full time",
    "performance": "Very Good",
    "activityStatus": "Inactive",
    "inactiveDays": 27,
    "contactNo": "9876510746"
  },
  {
    "id": "82",
    "regId": "45954941",
    "name": "Arjun Iyer",
    "email": "arjun.iyer82@example.com",
    "batch": "November 2025",
    "admissionDate": "2025-01-01",
    "daysWaiting": 0,
    "program": "Lakshya",
    "mode": "Online",
    "category": "College",
    "performance": "Poor",
    "activityStatus": "Inactive",
    "inactiveDays": 19,
    "contactNo": "9876540507",
    "assignedMentor": "Kavita Rao"
  },
  {
    "id": "83",
    "regId": "45954942",
    "name": "Raj Gupta",
    "email": "raj.gupta83@example.com",
    "batch": "November 2025",
    "admissionDate": "2025-01-01",
    "daysWaiting": 19,
    "program": "Lakshya",
    "mode": "Offline",
    "category": "Full time",
    "performance": "Very Good",
    "activityStatus": "Inactive",
    "inactiveDays": 28,
    "contactNo": "9876574928"
  },
  {
    "id": "84",
    "regId": "45954943",
    "name": "Ayan Bose",
    "email": "ayan.bose84@example.com",
    "batch": "November 2025",
    "admissionDate": "2025-01-01",
    "daysWaiting": 0,
    "program": "Lakshya",
    "mode": "Online",
    "category": "Full time",
    "performance": "Very Good",
    "activityStatus": "Active",
    "inactiveDays": 16,
    "contactNo": "9876568009",
    "assignedMentor": "Meera Reddy"
  },
  {
    "id": "85",
    "regId": "45954944",
    "name": "Shreya Chopra",
    "email": "shreya.chopra85@example.com",
    "batch": "November 2025",
    "admissionDate": "2025-01-01",
    "daysWaiting": 0,
    "program": "Lakshya",
    "mode": "Online",
    "category": "College",
    "performance": "Excellent",
    "activityStatus": "Inactive",
    "inactiveDays": 11,
    "contactNo": "9876538070",
    "assignedMentor": "Rajesh Koothrappali"
  },
  {
    "id": "86",
    "regId": "45954945",
    "name": "Anika Bose",
    "email": "anika.bose86@example.com",
    "batch": "November 2025",
    "admissionDate": "2025-01-01",
    "daysWaiting": 0,
    "program": "Lakshya",
    "mode": "Online",
    "category": "Full time",
    "performance": "Average",
    "activityStatus": "Inactive",
    "inactiveDays": 21,
    "contactNo": "9876596175",
    "assignedMentor": "Rajesh Koothrappali"
  },
  {
    "id": "87",
    "regId": "45954946",
    "name": "Shreya Patel",
    "email": "shreya.patel87@example.com",
    "batch": "November 2025",
    "admissionDate": "2025-01-01",
    "daysWaiting": 0,
    "program": "Lakshya",
    "mode": "Offline",
    "category": "Working",
    "performance": "Average",
    "activityStatus": "Active",
    "inactiveDays": 25,
    "contactNo": "9876514922",
    "assignedMentor": "Meera Reddy"
  },
  {
    "id": "88",
    "regId": "45954947",
    "name": "Arjun Jain",
    "email": "arjun.jain88@example.com",
    "batch": "November 2025",
    "admissionDate": "2025-01-01",
    "daysWaiting": 0,
    "program": "Lakshya",
    "mode": "Offline",
    "category": "Full time",
    "performance": "Good",
    "activityStatus": "Inactive",
    "inactiveDays": 26,
    "contactNo": "9876599227",
    "assignedMentor": "Kavita Rao"
  },
  {
    "id": "89",
    "regId": "45954948",
    "name": "Aadya Reddy",
    "email": "aadya.reddy89@example.com",
    "batch": "December 2025",
    "admissionDate": "2025-01-01",
    "daysWaiting": 0,
    "program": "Lakshya",
    "mode": "Offline",
    "category": "Full time",
    "performance": "Good",
    "activityStatus": "Active",
    "inactiveDays": 8,
    "contactNo": "9876512165",
    "assignedMentor": "Rajesh Koothrappali"
  },
  {
    "id": "90",
    "regId": "45954949",
    "name": "Neha Iyer",
    "email": "neha.iyer90@example.com",
    "batch": "December 2025",
    "admissionDate": "2025-01-01",
    "daysWaiting": 0,
    "program": "Lakshya",
    "mode": "Online",
    "category": "Full time",
    "performance": "Poor",
    "activityStatus": "Inactive",
    "inactiveDays": 23,
    "contactNo": "9876518680",
    "assignedMentor": "Rajesh Koothrappali"
  },
  {
    "id": "91",
    "regId": "45954950",
    "name": "Navya Mishra",
    "email": "navya.mishra91@example.com",
    "batch": "December 2025",
    "admissionDate": "2025-01-01",
    "daysWaiting": 24,
    "program": "Lakshya",
    "mode": "Offline",
    "category": "Working",
    "performance": "Good",
    "activityStatus": "Inactive",
    "inactiveDays": 10,
    "contactNo": "9876547625"
  },
  {
    "id": "92",
    "regId": "45954951",
    "name": "Amit Sharma",
    "email": "amit.sharma92@example.com",
    "batch": "December 2025",
    "admissionDate": "2025-01-01",
    "daysWaiting": 0,
    "program": "Lakshya",
    "mode": "Online",
    "category": "Full time",
    "performance": "Excellent",
    "activityStatus": "Active",
    "inactiveDays": 0,
    "contactNo": "9876579765",
    "assignedMentor": "Sanjay Dutt"
  },
  {
    "id": "93",
    "regId": "45954952",
    "name": "Ananya Bose",
    "email": "ananya.bose93@example.com",
    "batch": "December 2025",
    "admissionDate": "2025-01-01",
    "daysWaiting": 16,
    "program": "Lakshya",
    "mode": "Online",
    "category": "Full time",
    "performance": "Good",
    "activityStatus": "Inactive",
    "inactiveDays": 15,
    "contactNo": "9876521601"
  },
  {
    "id": "94",
    "regId": "45954953",
    "name": "Ayan Yadav",
    "email": "ayan.yadav94@example.com",
    "batch": "December 2025",
    "admissionDate": "2025-01-01",
    "daysWaiting": 0,
    "program": "Lakshya",
    "mode": "Offline",
    "category": "College",
    "performance": "Average",
    "activityStatus": "Active",
    "inactiveDays": 14,
    "contactNo": "9876523637",
    "assignedMentor": "Sanjay Dutt"
  },
  {
    "id": "95",
    "regId": "45954954",
    "name": "Vihaan Rao",
    "email": "vihaan.rao95@example.com",
    "batch": "December 2025",
    "admissionDate": "2025-01-01",
    "daysWaiting": 3,
    "program": "Lakshya",
    "mode": "Online",
    "category": "College",
    "performance": "Very Good",
    "activityStatus": "Active",
    "inactiveDays": 3,
    "contactNo": "9876521934"
  },
  {
    "id": "96",
    "regId": "45954955",
    "name": "Vikram Bose",
    "email": "vikram.bose96@example.com",
    "batch": "December 2025",
    "admissionDate": "2025-01-01",
    "daysWaiting": 0,
    "program": "Lakshya",
    "mode": "Online",
    "category": "College",
    "performance": "Average",
    "activityStatus": "Active",
    "inactiveDays": 2,
    "contactNo": "9876531931",
    "assignedMentor": "Kavita Rao"
  },
  {
    "id": "97",
    "regId": "45954956",
    "name": "Vivaan Jain",
    "email": "vivaan.jain97@example.com",
    "batch": "December 2025",
    "admissionDate": "2025-01-01",
    "daysWaiting": 0,
    "program": "Lakshya",
    "mode": "Online",
    "category": "College",
    "performance": "Very Good",
    "activityStatus": "Active",
    "inactiveDays": 25,
    "contactNo": "9876560029",
    "assignedMentor": "Arjun Mehta"
  },
  {
    "id": "98",
    "regId": "45954957",
    "name": "Amit Kumar",
    "email": "amit.kumar98@example.com",
    "batch": "December 2025",
    "admissionDate": "2025-01-01",
    "daysWaiting": 19,
    "program": "Lakshya",
    "mode": "Online",
    "category": "College",
    "performance": "Average",
    "activityStatus": "Active",
    "inactiveDays": 11,
    "contactNo": "9876546443"
  },
  {
    "id": "99",
    "regId": "45954958",
    "name": "Raj Mishra",
    "email": "raj.mishra99@example.com",
    "batch": "December 2025",
    "admissionDate": "2025-01-01",
    "daysWaiting": 0,
    "program": "Lakshya",
    "mode": "Offline",
    "category": "Full time",
    "performance": "Excellent",
    "activityStatus": "Active",
    "inactiveDays": 16,
    "contactNo": "9876515226",
    "assignedMentor": "Meera Reddy"
  },
  {
    "id": "100",
    "regId": "45954959",
    "name": "Anika Chatterjee",
    "email": "anika.chatterjee100@example.com",
    "batch": "December 2025",
    "admissionDate": "2025-01-01",
    "daysWaiting": 30,
    "program": "Lakshya",
    "mode": "Online",
    "category": "Full time",
    "performance": "Very Good",
    "activityStatus": "Inactive",
    "inactiveDays": 5,
    "contactNo": "9876540831"
  },
  {
    "id": "101",
    "regId": "45954960",
    "name": "Pooja Nair",
    "email": "pooja.nair101@example.com",
    "batch": "December 2025",
    "admissionDate": "2025-01-01",
    "daysWaiting": 0,
    "program": "Lakshya",
    "mode": "Offline",
    "category": "College",
    "performance": "Excellent",
    "activityStatus": "Inactive",
    "inactiveDays": 30,
    "contactNo": "9876579599",
    "assignedMentor": "Arjun Mehta"
  },
  {
    "id": "102",
    "regId": "45954961",
    "name": "Pari Nair",
    "email": "pari.nair102@example.com",
    "batch": "December 2025",
    "admissionDate": "2025-01-01",
    "daysWaiting": 17,
    "program": "Lakshya",
    "mode": "Online",
    "category": "College",
    "performance": "Poor",
    "activityStatus": "Inactive",
    "inactiveDays": 14,
    "contactNo": "9876563696"
  },
  {
    "id": "103",
    "regId": "45954962",
    "name": "Ishaan Mishra",
    "email": "ishaan.mishra103@example.com",
    "batch": "December 2025",
    "admissionDate": "2025-01-01",
    "daysWaiting": 0,
    "program": "Lakshya",
    "mode": "Online",
    "category": "Working",
    "performance": "Excellent",
    "activityStatus": "Active",
    "inactiveDays": 25,
    "contactNo": "9876588017",
    "assignedMentor": "Arjun Mehta"
  },
  {
    "id": "104",
    "regId": "45954963",
    "name": "Aarav Malhotra",
    "email": "aarav.malhotra104@example.com",
    "batch": "January 2026",
    "admissionDate": "2025-01-01",
    "daysWaiting": 0,
    "program": "Lakshya",
    "mode": "Online",
    "category": "Working",
    "performance": "Very Good",
    "activityStatus": "Active",
    "inactiveDays": 11,
    "contactNo": "9876570104",
    "assignedMentor": "Arjun Mehta"
  },
  {
    "id": "105",
    "regId": "45954964",
    "name": "Rahul Iyer",
    "email": "rahul.iyer105@example.com",
    "batch": "January 2026",
    "admissionDate": "2025-01-01",
    "daysWaiting": 28,
    "program": "Lakshya",
    "mode": "Offline",
    "category": "Working",
    "performance": "Average",
    "activityStatus": "Active",
    "inactiveDays": 7,
    "contactNo": "9876560398"
  },
  {
    "id": "106",
    "regId": "45954965",
    "name": "Shreya Sharma",
    "email": "shreya.sharma106@example.com",
    "batch": "January 2026",
    "admissionDate": "2025-01-01",
    "daysWaiting": 0,
    "program": "Lakshya",
    "mode": "Online",
    "category": "College",
    "performance": "Good",
    "activityStatus": "Active",
    "inactiveDays": 6,
    "contactNo": "9876576491",
    "assignedMentor": "Rajesh Koothrappali"
  },
  {
    "id": "107",
    "regId": "45954966",
    "name": "Ishaan Das",
    "email": "ishaan.das107@example.com",
    "batch": "January 2026",
    "admissionDate": "2025-01-01",
    "daysWaiting": 7,
    "program": "Lakshya",
    "mode": "Offline",
    "category": "Working",
    "performance": "Poor",
    "activityStatus": "Inactive",
    "inactiveDays": 26,
    "contactNo": "9876549936"
  },
  {
    "id": "108",
    "regId": "45954967",
    "name": "Vivaan Singh",
    "email": "vivaan.singh108@example.com",
    "batch": "January 2026",
    "admissionDate": "2025-01-01",
    "daysWaiting": 29,
    "program": "Lakshya",
    "mode": "Offline",
    "category": "College",
    "performance": "Excellent",
    "activityStatus": "Active",
    "inactiveDays": 23,
    "contactNo": "9876595584"
  },
  {
    "id": "109",
    "regId": "45954968",
    "name": "Aadya Mehta",
    "email": "aadya.mehta109@example.com",
    "batch": "January 2026",
    "admissionDate": "2025-01-01",
    "daysWaiting": 20,
    "program": "Lakshya",
    "mode": "Online",
    "category": "Full time",
    "performance": "Poor",
    "activityStatus": "Active",
    "inactiveDays": 10,
    "contactNo": "9876572709"
  },
  {
    "id": "110",
    "regId": "45954969",
    "name": "Aditya Singh",
    "email": "aditya.singh110@example.com",
    "batch": "January 2026",
    "admissionDate": "2025-01-01",
    "daysWaiting": 23,
    "program": "Lakshya",
    "mode": "Offline",
    "category": "College",
    "performance": "Excellent",
    "activityStatus": "Inactive",
    "inactiveDays": 18,
    "contactNo": "9876547868"
  },
  {
    "id": "111",
    "regId": "45954970",
    "name": "Pooja Malhotra",
    "email": "pooja.malhotra111@example.com",
    "batch": "January 2026",
    "admissionDate": "2025-01-01",
    "daysWaiting": 2,
    "program": "Lakshya",
    "mode": "Online",
    "category": "Full time",
    "performance": "Good",
    "activityStatus": "Active",
    "inactiveDays": 28,
    "contactNo": "9876553728"
  },
  {
    "id": "112",
    "regId": "45954971",
    "name": "Amit Mehta",
    "email": "amit.mehta112@example.com",
    "batch": "January 2026",
    "admissionDate": "2025-01-01",
    "daysWaiting": 0,
    "program": "Lakshya",
    "mode": "Offline",
    "category": "Full time",
    "performance": "Very Good",
    "activityStatus": "Inactive",
    "inactiveDays": 24,
    "contactNo": "9876520299",
    "assignedMentor": "Kavita Rao"
  },
  {
    "id": "113",
    "regId": "45954972",
    "name": "Sneha Mishra",
    "email": "sneha.mishra113@example.com",
    "batch": "January 2026",
    "admissionDate": "2025-01-01",
    "daysWaiting": 24,
    "program": "Lakshya",
    "mode": "Online",
    "category": "Working",
    "performance": "Excellent",
    "activityStatus": "Active",
    "inactiveDays": 9,
    "contactNo": "9876559957"
  },
  {
    "id": "114",
    "regId": "45954973",
    "name": "Pooja Das",
    "email": "pooja.das114@example.com",
    "batch": "January 2026",
    "admissionDate": "2025-01-01",
    "daysWaiting": 22,
    "program": "Lakshya",
    "mode": "Online",
    "category": "College",
    "performance": "Average",
    "activityStatus": "Inactive",
    "inactiveDays": 5,
    "contactNo": "9876574804"
  },
  {
    "id": "115",
    "regId": "45954974",
    "name": "Krishna Mishra",
    "email": "krishna.mishra115@example.com",
    "batch": "January 2026",
    "admissionDate": "2025-01-01",
    "daysWaiting": 13,
    "program": "Lakshya",
    "mode": "Online",
    "category": "Full time",
    "performance": "Poor",
    "activityStatus": "Active",
    "inactiveDays": 14,
    "contactNo": "9876543488"
  },
  {
    "id": "116",
    "regId": "45954975",
    "name": "Anika Singh",
    "email": "anika.singh116@example.com",
    "batch": "January 2026",
    "admissionDate": "2025-01-01",
    "daysWaiting": 6,
    "program": "Lakshya",
    "mode": "Offline",
    "category": "Full time",
    "performance": "Very Good",
    "activityStatus": "Inactive",
    "inactiveDays": 19,
    "contactNo": "9876569805"
  },
  {
    "id": "117",
    "regId": "45954976",
    "name": "Vikram Iyer",
    "email": "vikram.iyer117@example.com",
    "batch": "January 2026",
    "admissionDate": "2025-01-01",
    "daysWaiting": 0,
    "program": "Lakshya",
    "mode": "Online",
    "category": "Working",
    "performance": "Good",
    "activityStatus": "Inactive",
    "inactiveDays": 29,
    "contactNo": "9876553616",
    "assignedMentor": "Kavita Rao"
  },
  {
    "id": "118",
    "regId": "45954977",
    "name": "Neha Rao",
    "email": "neha.rao118@example.com",
    "batch": "February 2026",
    "admissionDate": "2025-01-01",
    "daysWaiting": 23,
    "program": "Lakshya",
    "mode": "Offline",
    "category": "Working",
    "performance": "Good",
    "activityStatus": "Active",
    "inactiveDays": 27,
    "contactNo": "9876582627"
  },
  {
    "id": "119",
    "regId": "45954978",
    "name": "Ishaan Gupta",
    "email": "ishaan.gupta119@example.com",
    "batch": "February 2026",
    "admissionDate": "2025-01-01",
    "daysWaiting": 21,
    "program": "Lakshya",
    "mode": "Offline",
    "category": "Full time",
    "performance": "Poor",
    "activityStatus": "Inactive",
    "inactiveDays": 9,
    "contactNo": "9876589242"
  },
  {
    "id": "120",
    "regId": "45954979",
    "name": "Neha Das",
    "email": "neha.das120@example.com",
    "batch": "February 2026",
    "admissionDate": "2025-01-01",
    "daysWaiting": 0,
    "program": "Lakshya",
    "mode": "Online",
    "category": "College",
    "performance": "Average",
    "activityStatus": "Inactive",
    "inactiveDays": 11,
    "contactNo": "9876527233",
    "assignedMentor": "Arjun Mehta"
  },
  {
    "id": "121",
    "regId": "45954980",
    "name": "Vihaan Jain",
    "email": "vihaan.jain121@example.com",
    "batch": "February 2026",
    "admissionDate": "2025-01-01",
    "daysWaiting": 11,
    "program": "Lakshya",
    "mode": "Online",
    "category": "Full time",
    "performance": "Good",
    "activityStatus": "Inactive",
    "inactiveDays": 26,
    "contactNo": "9876586141"
  },
  {
    "id": "122",
    "regId": "45954981",
    "name": "Pari Reddy",
    "email": "pari.reddy122@example.com",
    "batch": "February 2026",
    "admissionDate": "2025-01-01",
    "daysWaiting": 0,
    "program": "Lakshya",
    "mode": "Online",
    "category": "Full time",
    "performance": "Good",
    "activityStatus": "Inactive",
    "inactiveDays": 29,
    "contactNo": "9876544200",
    "assignedMentor": "Arjun Mehta"
  },
  {
    "id": "123",
    "regId": "45954982",
    "name": "Vihaan Chatterjee",
    "email": "vihaan.chatterjee123@example.com",
    "batch": "February 2026",
    "admissionDate": "2025-01-01",
    "daysWaiting": 0,
    "program": "Lakshya",
    "mode": "Offline",
    "category": "Working",
    "performance": "Poor",
    "activityStatus": "Active",
    "inactiveDays": 13,
    "contactNo": "9876562362",
    "assignedMentor": "Rajesh Koothrappali"
  },
  {
    "id": "124",
    "regId": "45954983",
    "name": "Priya Chatterjee",
    "email": "priya.chatterjee124@example.com",
    "batch": "February 2026",
    "admissionDate": "2025-01-01",
    "daysWaiting": 0,
    "program": "Lakshya",
    "mode": "Online",
    "category": "Full time",
    "performance": "Average",
    "activityStatus": "Active",
    "inactiveDays": 0,
    "contactNo": "9876583400",
    "assignedMentor": "Sanjay Dutt"
  },
  {
    "id": "125",
    "regId": "45954984",
    "name": "Ayan Rao",
    "email": "ayan.rao125@example.com",
    "batch": "February 2026",
    "admissionDate": "2025-01-01",
    "daysWaiting": 11,
    "program": "Lakshya",
    "mode": "Offline",
    "category": "Full time",
    "performance": "Average",
    "activityStatus": "Inactive",
    "inactiveDays": 7,
    "contactNo": "9876572806"
  },
  {
    "id": "126",
    "regId": "45954985",
    "name": "Sneha Singh",
    "email": "sneha.singh126@example.com",
    "batch": "February 2026",
    "admissionDate": "2025-01-01",
    "daysWaiting": 2,
    "program": "Lakshya",
    "mode": "Offline",
    "category": "Full time",
    "performance": "Good",
    "activityStatus": "Inactive",
    "inactiveDays": 20,
    "contactNo": "9876523399"
  },
  {
    "id": "127",
    "regId": "45954986",
    "name": "Shreya Jain",
    "email": "shreya.jain127@example.com",
    "batch": "February 2026",
    "admissionDate": "2025-01-01",
    "daysWaiting": 27,
    "program": "Lakshya",
    "mode": "Online",
    "category": "Full time",
    "performance": "Excellent",
    "activityStatus": "Inactive",
    "inactiveDays": 3,
    "contactNo": "9876555789"
  },
  {
    "id": "128",
    "regId": "45954987",
    "name": "Aarav Mishra",
    "email": "aarav.mishra128@example.com",
    "batch": "February 2026",
    "admissionDate": "2025-01-01",
    "daysWaiting": 0,
    "program": "Lakshya",
    "mode": "Online",
    "category": "College",
    "performance": "Very Good",
    "activityStatus": "Active",
    "inactiveDays": 21,
    "contactNo": "9876579927",
    "assignedMentor": "Arjun Mehta"
  },
  {
    "id": "129",
    "regId": "45954988",
    "name": "Pooja Jain",
    "email": "pooja.jain129@example.com",
    "batch": "February 2026",
    "admissionDate": "2025-01-01",
    "daysWaiting": 0,
    "program": "Lakshya",
    "mode": "Online",
    "category": "Full time",
    "performance": "Average",
    "activityStatus": "Inactive",
    "inactiveDays": 15,
    "contactNo": "9876540594",
    "assignedMentor": "Kavita Rao"
  },
  {
    "id": "130",
    "regId": "45954989",
    "name": "Rahul Das",
    "email": "rahul.das130@example.com",
    "batch": "February 2026",
    "admissionDate": "2025-01-01",
    "daysWaiting": 25,
    "program": "Lakshya",
    "mode": "Online",
    "category": "College",
    "performance": "Average",
    "activityStatus": "Inactive",
    "inactiveDays": 17,
    "contactNo": "9876554263"
  },
  {
    "id": "131",
    "regId": "45954990",
    "name": "Rohan Mishra",
    "email": "rohan.mishra131@example.com",
    "batch": "March 2026",
    "admissionDate": "2025-01-01",
    "daysWaiting": 13,
    "program": "Lakshya",
    "mode": "Offline",
    "category": "Full time",
    "performance": "Good",
    "activityStatus": "Inactive",
    "inactiveDays": 25,
    "contactNo": "9876559762"
  },
  {
    "id": "132",
    "regId": "45954991",
    "name": "Pari Iyer",
    "email": "pari.iyer132@example.com",
    "batch": "March 2026",
    "admissionDate": "2025-01-01",
    "daysWaiting": 0,
    "program": "Lakshya",
    "mode": "Online",
    "category": "Full time",
    "performance": "Poor",
    "activityStatus": "Inactive",
    "inactiveDays": 1,
    "contactNo": "9876550125",
    "assignedMentor": "Meera Reddy"
  },
  {
    "id": "133",
    "regId": "45954992",
    "name": "Rohan Chopra",
    "email": "rohan.chopra133@example.com",
    "batch": "March 2026",
    "admissionDate": "2025-01-01",
    "daysWaiting": 30,
    "program": "Lakshya",
    "mode": "Offline",
    "category": "Full time",
    "performance": "Very Good",
    "activityStatus": "Active",
    "inactiveDays": 6,
    "contactNo": "9876584933"
  },
  {
    "id": "134",
    "regId": "45954993",
    "name": "Sneha Gupta",
    "email": "sneha.gupta134@example.com",
    "batch": "March 2026",
    "admissionDate": "2025-01-01",
    "daysWaiting": 0,
    "program": "Lakshya",
    "mode": "Online",
    "category": "Working",
    "performance": "Excellent",
    "activityStatus": "Inactive",
    "inactiveDays": 11,
    "contactNo": "9876534953",
    "assignedMentor": "Kavita Rao"
  },
  {
    "id": "135",
    "regId": "45954994",
    "name": "Diya Patel",
    "email": "diya.patel135@example.com",
    "batch": "March 2026",
    "admissionDate": "2025-01-01",
    "daysWaiting": 0,
    "program": "Lakshya",
    "mode": "Offline",
    "category": "College",
    "performance": "Very Good",
    "activityStatus": "Active",
    "inactiveDays": 22,
    "contactNo": "9876577604",
    "assignedMentor": "Sanjay Dutt"
  },
  {
    "id": "136",
    "regId": "45954995",
    "name": "Raj Singh",
    "email": "raj.singh136@example.com",
    "batch": "March 2026",
    "admissionDate": "2025-01-01",
    "daysWaiting": 0,
    "program": "Lakshya",
    "mode": "Offline",
    "category": "Working",
    "performance": "Excellent",
    "activityStatus": "Active",
    "inactiveDays": 27,
    "contactNo": "9876544294",
    "assignedMentor": "Sanjay Dutt"
  },
  {
    "id": "137",
    "regId": "45954996",
    "name": "Anya Gupta",
    "email": "anya.gupta137@example.com",
    "batch": "March 2026",
    "admissionDate": "2025-01-01",
    "daysWaiting": 27,
    "program": "Lakshya",
    "mode": "Online",
    "category": "Working",
    "performance": "Excellent",
    "activityStatus": "Inactive",
    "inactiveDays": 26,
    "contactNo": "9876561437"
  },
  {
    "id": "138",
    "regId": "45954997",
    "name": "Rohan Malhotra",
    "email": "rohan.malhotra138@example.com",
    "batch": "March 2026",
    "admissionDate": "2025-01-01",
    "daysWaiting": 0,
    "program": "Lakshya",
    "mode": "Offline",
    "category": "Full time",
    "performance": "Excellent",
    "activityStatus": "Inactive",
    "inactiveDays": 13,
    "contactNo": "9876574075",
    "assignedMentor": "Rajesh Koothrappali"
  },
  {
    "id": "139",
    "regId": "45954998",
    "name": "Vivaan Jain",
    "email": "vivaan.jain139@example.com",
    "batch": "March 2026",
    "admissionDate": "2025-01-01",
    "daysWaiting": 22,
    "program": "Lakshya",
    "mode": "Online",
    "category": "Full time",
    "performance": "Average",
    "activityStatus": "Inactive",
    "inactiveDays": 2,
    "contactNo": "9876560116"
  },
  {
    "id": "140",
    "regId": "45954999",
    "name": "Aadya Kumar",
    "email": "aadya.kumar140@example.com",
    "batch": "March 2026",
    "admissionDate": "2025-01-01",
    "daysWaiting": 0,
    "program": "Lakshya",
    "mode": "Online",
    "category": "College",
    "performance": "Very Good",
    "activityStatus": "Inactive",
    "inactiveDays": 28,
    "contactNo": "9876564549",
    "assignedMentor": "Sanjay Dutt"
  },
  {
    "id": "141",
    "regId": "45955000",
    "name": "Anya Patel",
    "email": "anya.patel141@example.com",
    "batch": "March 2026",
    "admissionDate": "2025-01-01",
    "daysWaiting": 21,
    "program": "Lakshya",
    "mode": "Online",
    "category": "Full time",
    "performance": "Poor",
    "activityStatus": "Inactive",
    "inactiveDays": 21,
    "contactNo": "9876510878"
  },
  {
    "id": "142",
    "regId": "45955001",
    "name": "Arjun Verma",
    "email": "arjun.verma142@example.com",
    "batch": "March 2026",
    "admissionDate": "2025-01-01",
    "daysWaiting": 22,
    "program": "Lakshya",
    "mode": "Online",
    "category": "Full time",
    "performance": "Excellent",
    "activityStatus": "Active",
    "inactiveDays": 3,
    "contactNo": "9876520932"
  },
  {
    "id": "143",
    "regId": "45955002",
    "name": "Rohan Chatterjee",
    "email": "rohan.chatterjee143@example.com",
    "batch": "March 2026",
    "admissionDate": "2025-01-01",
    "daysWaiting": 29,
    "program": "Lakshya",
    "mode": "Online",
    "category": "College",
    "performance": "Average",
    "activityStatus": "Active",
    "inactiveDays": 9,
    "contactNo": "9876545208"
  },
  {
    "id": "144",
    "regId": "45955003",
    "name": "Sneha Sharma",
    "email": "sneha.sharma144@example.com",
    "batch": "March 2026",
    "admissionDate": "2025-01-01",
    "daysWaiting": 0,
    "program": "Lakshya",
    "mode": "Online",
    "category": "College",
    "performance": "Good",
    "activityStatus": "Active",
    "inactiveDays": 27,
    "contactNo": "9876566534",
    "assignedMentor": "Rajesh Koothrappali"
  },
  {
    "id": "145",
    "regId": "45955004",
    "name": "Reyansh Chopra",
    "email": "reyansh.chopra145@example.com",
    "batch": "March 2026",
    "admissionDate": "2025-01-01",
    "daysWaiting": 0,
    "program": "Lakshya",
    "mode": "Offline",
    "category": "Full time",
    "performance": "Good",
    "activityStatus": "Active",
    "inactiveDays": 21,
    "contactNo": "9876571800",
    "assignedMentor": "Arjun Mehta"
  },
  {
    "id": "146",
    "regId": "45955005",
    "name": "Myra Gupta",
    "email": "myra.gupta146@example.com",
    "batch": "November 2025",
    "admissionDate": "2025-01-01",
    "daysWaiting": 1,
    "program": "Dakshya",
    "mode": "Online",
    "category": "College",
    "performance": "Good",
    "activityStatus": "Inactive",
    "inactiveDays": 14,
    "contactNo": "9876542090"
  },
  {
    "id": "147",
    "regId": "45955006",
    "name": "Pari Mehta",
    "email": "pari.mehta147@example.com",
    "batch": "November 2025",
    "admissionDate": "2025-01-01",
    "daysWaiting": 0,
    "program": "Dakshya",
    "mode": "Online",
    "category": "Working",
    "performance": "Average",
    "activityStatus": "Active",
    "inactiveDays": 6,
    "contactNo": "9876583665",
    "assignedMentor": "Rajesh Koothrappali"
  },
  {
    "id": "148",
    "regId": "45955007",
    "name": "Vikram Malhotra",
    "email": "vikram.malhotra148@example.com",
    "batch": "November 2025",
    "admissionDate": "2025-01-01",
    "daysWaiting": 2,
    "program": "Dakshya",
    "mode": "Offline",
    "category": "Working",
    "performance": "Very Good",
    "activityStatus": "Inactive",
    "inactiveDays": 0,
    "contactNo": "9876513774"
  },
  {
    "id": "149",
    "regId": "45955008",
    "name": "Vikram Rao",
    "email": "vikram.rao149@example.com",
    "batch": "November 2025",
    "admissionDate": "2025-01-01",
    "daysWaiting": 9,
    "program": "Dakshya",
    "mode": "Offline",
    "category": "Full time",
    "performance": "Good",
    "activityStatus": "Inactive",
    "inactiveDays": 30,
    "contactNo": "9876551407"
  },
  {
    "id": "150",
    "regId": "45955009",
    "name": "Diya Das",
    "email": "diya.das150@example.com",
    "batch": "November 2025",
    "admissionDate": "2025-01-01",
    "daysWaiting": 21,
    "program": "Dakshya",
    "mode": "Offline",
    "category": "College",
    "performance": "Average",
    "activityStatus": "Inactive",
    "inactiveDays": 8,
    "contactNo": "9876533559"
  },
  {
    "id": "151",
    "regId": "45955010",
    "name": "Rahul Mishra",
    "email": "rahul.mishra151@example.com",
    "batch": "November 2025",
    "admissionDate": "2025-01-01",
    "daysWaiting": 6,
    "program": "Dakshya",
    "mode": "Offline",
    "category": "Full time",
    "performance": "Very Good",
    "activityStatus": "Active",
    "inactiveDays": 2,
    "contactNo": "9876528206"
  },
  {
    "id": "152",
    "regId": "45955011",
    "name": "Myra Nair",
    "email": "myra.nair152@example.com",
    "batch": "November 2025",
    "admissionDate": "2025-01-01",
    "daysWaiting": 14,
    "program": "Dakshya",
    "mode": "Online",
    "category": "Working",
    "performance": "Good",
    "activityStatus": "Inactive",
    "inactiveDays": 17,
    "contactNo": "9876587902"
  },
  {
    "id": "153",
    "regId": "45955012",
    "name": "Aarav Rao",
    "email": "aarav.rao153@example.com",
    "batch": "November 2025",
    "admissionDate": "2025-01-01",
    "daysWaiting": 17,
    "program": "Dakshya",
    "mode": "Offline",
    "category": "College",
    "performance": "Very Good",
    "activityStatus": "Active",
    "inactiveDays": 15,
    "contactNo": "9876589956"
  },
  {
    "id": "154",
    "regId": "45955013",
    "name": "Myra Jain",
    "email": "myra.jain154@example.com",
    "batch": "November 2025",
    "admissionDate": "2025-01-01",
    "daysWaiting": 0,
    "program": "Dakshya",
    "mode": "Offline",
    "category": "Full time",
    "performance": "Poor",
    "activityStatus": "Inactive",
    "inactiveDays": 25,
    "contactNo": "9876534860",
    "assignedMentor": "Arjun Mehta"
  },
  {
    "id": "155",
    "regId": "45955014",
    "name": "Anika Sharma",
    "email": "anika.sharma155@example.com",
    "batch": "November 2025",
    "admissionDate": "2025-01-01",
    "daysWaiting": 0,
    "program": "Dakshya",
    "mode": "Online",
    "category": "Full time",
    "performance": "Excellent",
    "activityStatus": "Inactive",
    "inactiveDays": 3,
    "contactNo": "9876541276",
    "assignedMentor": "Meera Reddy"
  },
  {
    "id": "156",
    "regId": "45955015",
    "name": "Arjun Chopra",
    "email": "arjun.chopra156@example.com",
    "batch": "November 2025",
    "admissionDate": "2025-01-01",
    "daysWaiting": 0,
    "program": "Dakshya",
    "mode": "Offline",
    "category": "Full time",
    "performance": "Excellent",
    "activityStatus": "Inactive",
    "inactiveDays": 5,
    "contactNo": "9876557633",
    "assignedMentor": "Arjun Mehta"
  },
  {
    "id": "157",
    "regId": "45955016",
    "name": "Rohan Kumar",
    "email": "rohan.kumar157@example.com",
    "batch": "November 2025",
    "admissionDate": "2025-01-01",
    "daysWaiting": 24,
    "program": "Dakshya",
    "mode": "Offline",
    "category": "College",
    "performance": "Average",
    "activityStatus": "Inactive",
    "inactiveDays": 7,
    "contactNo": "9876541267"
  },
  {
    "id": "158",
    "regId": "45955017",
    "name": "Ishaan Verma",
    "email": "ishaan.verma158@example.com",
    "batch": "November 2025",
    "admissionDate": "2025-01-01",
    "daysWaiting": 0,
    "program": "Dakshya",
    "mode": "Offline",
    "category": "Working",
    "performance": "Poor",
    "activityStatus": "Inactive",
    "inactiveDays": 5,
    "contactNo": "9876571860",
    "assignedMentor": "Sanjay Dutt"
  },
  {
    "id": "159",
    "regId": "45955018",
    "name": "Riya Kumar",
    "email": "riya.kumar159@example.com",
    "batch": "December 2025",
    "admissionDate": "2025-01-01",
    "daysWaiting": 0,
    "program": "Dakshya",
    "mode": "Offline",
    "category": "College",
    "performance": "Excellent",
    "activityStatus": "Active",
    "inactiveDays": 4,
    "contactNo": "9876554033",
    "assignedMentor": "Arjun Mehta"
  },
  {
    "id": "160",
    "regId": "45955019",
    "name": "Amit Das",
    "email": "amit.das160@example.com",
    "batch": "December 2025",
    "admissionDate": "2025-01-01",
    "daysWaiting": 0,
    "program": "Dakshya",
    "mode": "Online",
    "category": "College",
    "performance": "Average",
    "activityStatus": "Inactive",
    "inactiveDays": 27,
    "contactNo": "9876552113",
    "assignedMentor": "Kavita Rao"
  },
  {
    "id": "161",
    "regId": "45955020",
    "name": "Diya Kumar",
    "email": "diya.kumar161@example.com",
    "batch": "December 2025",
    "admissionDate": "2025-01-01",
    "daysWaiting": 30,
    "program": "Dakshya",
    "mode": "Offline",
    "category": "College",
    "performance": "Excellent",
    "activityStatus": "Active",
    "inactiveDays": 30,
    "contactNo": "9876553785"
  },
  {
    "id": "162",
    "regId": "45955021",
    "name": "Aadya Mishra",
    "email": "aadya.mishra162@example.com",
    "batch": "December 2025",
    "admissionDate": "2025-01-01",
    "daysWaiting": 0,
    "program": "Dakshya",
    "mode": "Online",
    "category": "Working",
    "performance": "Excellent",
    "activityStatus": "Inactive",
    "inactiveDays": 8,
    "contactNo": "9876561997",
    "assignedMentor": "Arjun Mehta"
  },
  {
    "id": "163",
    "regId": "45955022",
    "name": "Sai Jain",
    "email": "sai.jain163@example.com",
    "batch": "December 2025",
    "admissionDate": "2025-01-01",
    "daysWaiting": 27,
    "program": "Dakshya",
    "mode": "Offline",
    "category": "Working",
    "performance": "Average",
    "activityStatus": "Inactive",
    "inactiveDays": 0,
    "contactNo": "9876539592"
  },
  {
    "id": "164",
    "regId": "45955023",
    "name": "Pooja Mishra",
    "email": "pooja.mishra164@example.com",
    "batch": "December 2025",
    "admissionDate": "2025-01-01",
    "daysWaiting": 13,
    "program": "Dakshya",
    "mode": "Offline",
    "category": "Working",
    "performance": "Average",
    "activityStatus": "Active",
    "inactiveDays": 0,
    "contactNo": "9876539715"
  },
  {
    "id": "165",
    "regId": "45955024",
    "name": "Vikram Chatterjee",
    "email": "vikram.chatterjee165@example.com",
    "batch": "December 2025",
    "admissionDate": "2025-01-01",
    "daysWaiting": 0,
    "program": "Dakshya",
    "mode": "Offline",
    "category": "Full time",
    "performance": "Good",
    "activityStatus": "Inactive",
    "inactiveDays": 23,
    "contactNo": "9876558382",
    "assignedMentor": "Sanjay Dutt"
  },
  {
    "id": "166",
    "regId": "45955025",
    "name": "Amit Jain",
    "email": "amit.jain166@example.com",
    "batch": "December 2025",
    "admissionDate": "2025-01-01",
    "daysWaiting": 0,
    "program": "Dakshya",
    "mode": "Offline",
    "category": "Working",
    "performance": "Good",
    "activityStatus": "Inactive",
    "inactiveDays": 20,
    "contactNo": "9876516632",
    "assignedMentor": "Kavita Rao"
  },
  {
    "id": "167",
    "regId": "45955026",
    "name": "Ishaan Chopra",
    "email": "ishaan.chopra167@example.com",
    "batch": "December 2025",
    "admissionDate": "2025-01-01",
    "daysWaiting": 0,
    "program": "Dakshya",
    "mode": "Offline",
    "category": "Full time",
    "performance": "Poor",
    "activityStatus": "Active",
    "inactiveDays": 21,
    "contactNo": "9876546831",
    "assignedMentor": "Meera Reddy"
  },
  {
    "id": "168",
    "regId": "45955027",
    "name": "Ishaan Mehta",
    "email": "ishaan.mehta168@example.com",
    "batch": "December 2025",
    "admissionDate": "2025-01-01",
    "daysWaiting": 14,
    "program": "Dakshya",
    "mode": "Offline",
    "category": "College",
    "performance": "Average",
    "activityStatus": "Inactive",
    "inactiveDays": 21,
    "contactNo": "9876565964"
  },
  {
    "id": "169",
    "regId": "45955028",
    "name": "Arjun Bose",
    "email": "arjun.bose169@example.com",
    "batch": "December 2025",
    "admissionDate": "2025-01-01",
    "daysWaiting": 0,
    "program": "Dakshya",
    "mode": "Online",
    "category": "Full time",
    "performance": "Excellent",
    "activityStatus": "Inactive",
    "inactiveDays": 5,
    "contactNo": "9876519499",
    "assignedMentor": "Arjun Mehta"
  },
  {
    "id": "170",
    "regId": "45955029",
    "name": "Ishaan Bose",
    "email": "ishaan.bose170@example.com",
    "batch": "December 2025",
    "admissionDate": "2025-01-01",
    "daysWaiting": 0,
    "program": "Dakshya",
    "mode": "Online",
    "category": "Full time",
    "performance": "Good",
    "activityStatus": "Inactive",
    "inactiveDays": 3,
    "contactNo": "9876519974",
    "assignedMentor": "Arjun Mehta"
  },
  {
    "id": "171",
    "regId": "45955030",
    "name": "Ananya Sharma",
    "email": "ananya.sharma171@example.com",
    "batch": "December 2025",
    "admissionDate": "2025-01-01",
    "daysWaiting": 0,
    "program": "Dakshya",
    "mode": "Online",
    "category": "Full time",
    "performance": "Good",
    "activityStatus": "Inactive",
    "inactiveDays": 11,
    "contactNo": "9876567280",
    "assignedMentor": "Kavita Rao"
  },
  {
    "id": "172",
    "regId": "45955031",
    "name": "Aadya Kumar",
    "email": "aadya.kumar172@example.com",
    "batch": "December 2025",
    "admissionDate": "2025-01-01",
    "daysWaiting": 15,
    "program": "Dakshya",
    "mode": "Offline",
    "category": "Full time",
    "performance": "Good",
    "activityStatus": "Inactive",
    "inactiveDays": 3,
    "contactNo": "9876599483"
  },
  {
    "id": "173",
    "regId": "45955032",
    "name": "Vivaan Das",
    "email": "vivaan.das173@example.com",
    "batch": "December 2025",
    "admissionDate": "2025-01-01",
    "daysWaiting": 10,
    "program": "Dakshya",
    "mode": "Online",
    "category": "Full time",
    "performance": "Excellent",
    "activityStatus": "Inactive",
    "inactiveDays": 9,
    "contactNo": "9876515581"
  },
  {
    "id": "174",
    "regId": "45955033",
    "name": "Krishna Yadav",
    "email": "krishna.yadav174@example.com",
    "batch": "January 2026",
    "admissionDate": "2025-01-01",
    "daysWaiting": 0,
    "program": "Dakshya",
    "mode": "Online",
    "category": "Working",
    "performance": "Good",
    "activityStatus": "Active",
    "inactiveDays": 27,
    "contactNo": "9876514562",
    "assignedMentor": "Sanjay Dutt"
  },
  {
    "id": "175",
    "regId": "45955034",
    "name": "Neha Kumar",
    "email": "neha.kumar175@example.com",
    "batch": "January 2026",
    "admissionDate": "2025-01-01",
    "daysWaiting": 0,
    "program": "Dakshya",
    "mode": "Offline",
    "category": "Full time",
    "performance": "Very Good",
    "activityStatus": "Active",
    "inactiveDays": 19,
    "contactNo": "9876592093",
    "assignedMentor": "Meera Reddy"
  },
  {
    "id": "176",
    "regId": "45955035",
    "name": "Anika Sharma",
    "email": "anika.sharma176@example.com",
    "batch": "January 2026",
    "admissionDate": "2025-01-01",
    "daysWaiting": 16,
    "program": "Dakshya",
    "mode": "Online",
    "category": "Working",
    "performance": "Very Good",
    "activityStatus": "Active",
    "inactiveDays": 15,
    "contactNo": "9876569755"
  },
  {
    "id": "177",
    "regId": "45955036",
    "name": "Ayan Mishra",
    "email": "ayan.mishra177@example.com",
    "batch": "January 2026",
    "admissionDate": "2025-01-01",
    "daysWaiting": 0,
    "program": "Dakshya",
    "mode": "Offline",
    "category": "College",
    "performance": "Good",
    "activityStatus": "Active",
    "inactiveDays": 2,
    "contactNo": "9876534729",
    "assignedMentor": "Kavita Rao"
  },
  {
    "id": "178",
    "regId": "45955037",
    "name": "Navya Das",
    "email": "navya.das178@example.com",
    "batch": "January 2026",
    "admissionDate": "2025-01-01",
    "daysWaiting": 0,
    "program": "Dakshya",
    "mode": "Online",
    "category": "Working",
    "performance": "Good",
    "activityStatus": "Inactive",
    "inactiveDays": 16,
    "contactNo": "9876542928",
    "assignedMentor": "Rajesh Koothrappali"
  },
  {
    "id": "179",
    "regId": "45955038",
    "name": "Anya Jain",
    "email": "anya.jain179@example.com",
    "batch": "January 2026",
    "admissionDate": "2025-01-01",
    "daysWaiting": 19,
    "program": "Dakshya",
    "mode": "Online",
    "category": "College",
    "performance": "Poor",
    "activityStatus": "Active",
    "inactiveDays": 8,
    "contactNo": "9876581479"
  },
  {
    "id": "180",
    "regId": "45955039",
    "name": "Neha Mishra",
    "email": "neha.mishra180@example.com",
    "batch": "January 2026",
    "admissionDate": "2025-01-01",
    "daysWaiting": 21,
    "program": "Dakshya",
    "mode": "Online",
    "category": "Full time",
    "performance": "Average",
    "activityStatus": "Active",
    "inactiveDays": 0,
    "contactNo": "9876535502"
  },
  {
    "id": "181",
    "regId": "45955040",
    "name": "Navya Singh",
    "email": "navya.singh181@example.com",
    "batch": "January 2026",
    "admissionDate": "2025-01-01",
    "daysWaiting": 0,
    "program": "Dakshya",
    "mode": "Online",
    "category": "College",
    "performance": "Very Good",
    "activityStatus": "Active",
    "inactiveDays": 1,
    "contactNo": "9876544077",
    "assignedMentor": "Sanjay Dutt"
  },
  {
    "id": "182",
    "regId": "45955041",
    "name": "Riya Reddy",
    "email": "riya.reddy182@example.com",
    "batch": "January 2026",
    "admissionDate": "2025-01-01",
    "daysWaiting": 27,
    "program": "Dakshya",
    "mode": "Offline",
    "category": "Full time",
    "performance": "Very Good",
    "activityStatus": "Inactive",
    "inactiveDays": 1,
    "contactNo": "9876513040"
  },
  {
    "id": "183",
    "regId": "45955042",
    "name": "Diya Saxena",
    "email": "diya.saxena183@example.com",
    "batch": "January 2026",
    "admissionDate": "2025-01-01",
    "daysWaiting": 0,
    "program": "Dakshya",
    "mode": "Online",
    "category": "College",
    "performance": "Poor",
    "activityStatus": "Active",
    "inactiveDays": 3,
    "contactNo": "9876586865",
    "assignedMentor": "Sanjay Dutt"
  },
  {
    "id": "184",
    "regId": "45955043",
    "name": "Pooja Reddy",
    "email": "pooja.reddy184@example.com",
    "batch": "January 2026",
    "admissionDate": "2025-01-01",
    "daysWaiting": 0,
    "program": "Dakshya",
    "mode": "Offline",
    "category": "Working",
    "performance": "Poor",
    "activityStatus": "Active",
    "inactiveDays": 6,
    "contactNo": "9876533044",
    "assignedMentor": "Meera Reddy"
  },
  {
    "id": "185",
    "regId": "45955044",
    "name": "Vivaan Malhotra",
    "email": "vivaan.malhotra185@example.com",
    "batch": "February 2026",
    "admissionDate": "2025-01-01",
    "daysWaiting": 10,
    "program": "Dakshya",
    "mode": "Online",
    "category": "Full time",
    "performance": "Excellent",
    "activityStatus": "Active",
    "inactiveDays": 5,
    "contactNo": "9876514877"
  },
  {
    "id": "186",
    "regId": "45955045",
    "name": "Navya Iyer",
    "email": "navya.iyer186@example.com",
    "batch": "February 2026",
    "admissionDate": "2025-01-01",
    "daysWaiting": 5,
    "program": "Dakshya",
    "mode": "Online",
    "category": "Full time",
    "performance": "Excellent",
    "activityStatus": "Active",
    "inactiveDays": 19,
    "contactNo": "9876568321"
  },
  {
    "id": "187",
    "regId": "45955046",
    "name": "Neha Nair",
    "email": "neha.nair187@example.com",
    "batch": "February 2026",
    "admissionDate": "2025-01-01",
    "daysWaiting": 0,
    "program": "Dakshya",
    "mode": "Offline",
    "category": "College",
    "performance": "Excellent",
    "activityStatus": "Active",
    "inactiveDays": 9,
    "contactNo": "9876512762",
    "assignedMentor": "Arjun Mehta"
  },
  {
    "id": "188",
    "regId": "45955047",
    "name": "Aarav Bose",
    "email": "aarav.bose188@example.com",
    "batch": "February 2026",
    "admissionDate": "2025-01-01",
    "daysWaiting": 16,
    "program": "Dakshya",
    "mode": "Online",
    "category": "Full time",
    "performance": "Average",
    "activityStatus": "Active",
    "inactiveDays": 22,
    "contactNo": "9876540754"
  },
  {
    "id": "189",
    "regId": "45955048",
    "name": "Diya Nair",
    "email": "diya.nair189@example.com",
    "batch": "February 2026",
    "admissionDate": "2025-01-01",
    "daysWaiting": 19,
    "program": "Dakshya",
    "mode": "Online",
    "category": "Full time",
    "performance": "Average",
    "activityStatus": "Active",
    "inactiveDays": 15,
    "contactNo": "9876589920"
  },
  {
    "id": "190",
    "regId": "45955049",
    "name": "Navya Jain",
    "email": "navya.jain190@example.com",
    "batch": "February 2026",
    "admissionDate": "2025-01-01",
    "daysWaiting": 0,
    "program": "Dakshya",
    "mode": "Offline",
    "category": "Full time",
    "performance": "Good",
    "activityStatus": "Active",
    "inactiveDays": 9,
    "contactNo": "9876528264",
    "assignedMentor": "Rajesh Koothrappali"
  },
  {
    "id": "191",
    "regId": "45955050",
    "name": "Myra Nair",
    "email": "myra.nair191@example.com",
    "batch": "February 2026",
    "admissionDate": "2025-01-01",
    "daysWaiting": 0,
    "program": "Dakshya",
    "mode": "Online",
    "category": "Working",
    "performance": "Good",
    "activityStatus": "Inactive",
    "inactiveDays": 24,
    "contactNo": "9876551597",
    "assignedMentor": "Kavita Rao"
  },
  {
    "id": "192",
    "regId": "45955051",
    "name": "Rahul Mishra",
    "email": "rahul.mishra192@example.com",
    "batch": "February 2026",
    "admissionDate": "2025-01-01",
    "daysWaiting": 0,
    "program": "Dakshya",
    "mode": "Offline",
    "category": "Full time",
    "performance": "Good",
    "activityStatus": "Inactive",
    "inactiveDays": 7,
    "contactNo": "9876590339",
    "assignedMentor": "Arjun Mehta"
  },
  {
    "id": "193",
    "regId": "45955052",
    "name": "Aarav Chatterjee",
    "email": "aarav.chatterjee193@example.com",
    "batch": "February 2026",
    "admissionDate": "2025-01-01",
    "daysWaiting": 0,
    "program": "Dakshya",
    "mode": "Online",
    "category": "Working",
    "performance": "Poor",
    "activityStatus": "Inactive",
    "inactiveDays": 22,
    "contactNo": "9876512407",
    "assignedMentor": "Meera Reddy"
  },
  {
    "id": "194",
    "regId": "45955053",
    "name": "Anya Jain",
    "email": "anya.jain194@example.com",
    "batch": "February 2026",
    "admissionDate": "2025-01-01",
    "daysWaiting": 26,
    "program": "Dakshya",
    "mode": "Online",
    "category": "Working",
    "performance": "Good",
    "activityStatus": "Inactive",
    "inactiveDays": 23,
    "contactNo": "9876540939"
  },
  {
    "id": "195",
    "regId": "45955054",
    "name": "Navya Kumar",
    "email": "navya.kumar195@example.com",
    "batch": "February 2026",
    "admissionDate": "2025-01-01",
    "daysWaiting": 7,
    "program": "Dakshya",
    "mode": "Offline",
    "category": "Working",
    "performance": "Average",
    "activityStatus": "Active",
    "inactiveDays": 19,
    "contactNo": "9876516052"
  },
  {
    "id": "196",
    "regId": "45955055",
    "name": "Anya Bose",
    "email": "anya.bose196@example.com",
    "batch": "February 2026",
    "admissionDate": "2025-01-01",
    "daysWaiting": 2,
    "program": "Dakshya",
    "mode": "Online",
    "category": "College",
    "performance": "Good",
    "activityStatus": "Active",
    "inactiveDays": 27,
    "contactNo": "9876555162"
  },
  {
    "id": "197",
    "regId": "45955056",
    "name": "Pari Saxena",
    "email": "pari.saxena197@example.com",
    "batch": "February 2026",
    "admissionDate": "2025-01-01",
    "daysWaiting": 0,
    "program": "Dakshya",
    "mode": "Offline",
    "category": "Full time",
    "performance": "Average",
    "activityStatus": "Active",
    "inactiveDays": 6,
    "contactNo": "9876550086",
    "assignedMentor": "Kavita Rao"
  },
  {
    "id": "198",
    "regId": "45955057",
    "name": "Riya Yadav",
    "email": "riya.yadav198@example.com",
    "batch": "March 2026",
    "admissionDate": "2025-01-01",
    "daysWaiting": 0,
    "program": "Dakshya",
    "mode": "Online",
    "category": "Working",
    "performance": "Poor",
    "activityStatus": "Inactive",
    "inactiveDays": 17,
    "contactNo": "9876526369",
    "assignedMentor": "Arjun Mehta"
  },
  {
    "id": "199",
    "regId": "45955058",
    "name": "Diya Mishra",
    "email": "diya.mishra199@example.com",
    "batch": "March 2026",
    "admissionDate": "2025-01-01",
    "daysWaiting": 0,
    "program": "Dakshya",
    "mode": "Offline",
    "category": "College",
    "performance": "Very Good",
    "activityStatus": "Inactive",
    "inactiveDays": 28,
    "contactNo": "9876598640",
    "assignedMentor": "Sanjay Dutt"
  },
  {
    "id": "200",
    "regId": "45955059",
    "name": "Vikram Reddy",
    "email": "vikram.reddy200@example.com",
    "batch": "March 2026",
    "admissionDate": "2025-01-01",
    "daysWaiting": 0,
    "program": "Dakshya",
    "mode": "Offline",
    "category": "College",
    "performance": "Good",
    "activityStatus": "Active",
    "inactiveDays": 13,
    "contactNo": "9876548652",
    "assignedMentor": "Meera Reddy"
  },
  {
    "id": "201",
    "regId": "45955060",
    "name": "Ayan Iyer",
    "email": "ayan.iyer201@example.com",
    "batch": "March 2026",
    "admissionDate": "2025-01-01",
    "daysWaiting": 0,
    "program": "Dakshya",
    "mode": "Online",
    "category": "Working",
    "performance": "Average",
    "activityStatus": "Active",
    "inactiveDays": 25,
    "contactNo": "9876511874",
    "assignedMentor": "Meera Reddy"
  },
  {
    "id": "202",
    "regId": "45955061",
    "name": "Aditya Reddy",
    "email": "aditya.reddy202@example.com",
    "batch": "March 2026",
    "admissionDate": "2025-01-01",
    "daysWaiting": 0,
    "program": "Dakshya",
    "mode": "Online",
    "category": "Full time",
    "performance": "Excellent",
    "activityStatus": "Inactive",
    "inactiveDays": 2,
    "contactNo": "9876544136",
    "assignedMentor": "Meera Reddy"
  },
  {
    "id": "203",
    "regId": "45955062",
    "name": "Krishna Das",
    "email": "krishna.das203@example.com",
    "batch": "March 2026",
    "admissionDate": "2025-01-01",
    "daysWaiting": 9,
    "program": "Dakshya",
    "mode": "Online",
    "category": "Full time",
    "performance": "Very Good",
    "activityStatus": "Active",
    "inactiveDays": 2,
    "contactNo": "9876520923"
  },
  {
    "id": "204",
    "regId": "45955063",
    "name": "Saanvi Yadav",
    "email": "saanvi.yadav204@example.com",
    "batch": "March 2026",
    "admissionDate": "2025-01-01",
    "daysWaiting": 25,
    "program": "Dakshya",
    "mode": "Online",
    "category": "Working",
    "performance": "Very Good",
    "activityStatus": "Inactive",
    "inactiveDays": 23,
    "contactNo": "9876590196"
  },
  {
    "id": "205",
    "regId": "45955064",
    "name": "Krishna Verma",
    "email": "krishna.verma205@example.com",
    "batch": "March 2026",
    "admissionDate": "2025-01-01",
    "daysWaiting": 0,
    "program": "Dakshya",
    "mode": "Online",
    "category": "College",
    "performance": "Very Good",
    "activityStatus": "Active",
    "inactiveDays": 11,
    "contactNo": "9876579538",
    "assignedMentor": "Rajesh Koothrappali"
  },
  {
    "id": "206",
    "regId": "45955065",
    "name": "Saanvi Iyer",
    "email": "saanvi.iyer206@example.com",
    "batch": "March 2026",
    "admissionDate": "2025-01-01",
    "daysWaiting": 18,
    "program": "Dakshya",
    "mode": "Offline",
    "category": "College",
    "performance": "Poor",
    "activityStatus": "Active",
    "inactiveDays": 28,
    "contactNo": "9876525613"
  },
  {
    "id": "207",
    "regId": "45955066",
    "name": "Pari Sharma",
    "email": "pari.sharma207@example.com",
    "batch": "March 2026",
    "admissionDate": "2025-01-01",
    "daysWaiting": 0,
    "program": "Dakshya",
    "mode": "Offline",
    "category": "Full time",
    "performance": "Poor",
    "activityStatus": "Active",
    "inactiveDays": 23,
    "contactNo": "9876595840",
    "assignedMentor": "Meera Reddy"
  },
  {
    "id": "208",
    "regId": "45955067",
    "name": "Vivaan Gupta",
    "email": "vivaan.gupta208@example.com",
    "batch": "March 2026",
    "admissionDate": "2025-01-01",
    "daysWaiting": 13,
    "program": "Dakshya",
    "mode": "Online",
    "category": "Working",
    "performance": "Poor",
    "activityStatus": "Inactive",
    "inactiveDays": 6,
    "contactNo": "9876515155"
  },
  {
    "id": "209",
    "regId": "45955068",
    "name": "Aadya Reddy",
    "email": "aadya.reddy209@example.com",
    "batch": "March 2026",
    "admissionDate": "2025-01-01",
    "daysWaiting": 25,
    "program": "Dakshya",
    "mode": "Online",
    "category": "Full time",
    "performance": "Very Good",
    "activityStatus": "Inactive",
    "inactiveDays": 7,
    "contactNo": "9876584840"
  },
  {
    "id": "210",
    "regId": "45955069",
    "name": "Shreya Chatterjee",
    "email": "shreya.chatterjee210@example.com",
    "batch": "March 2026",
    "admissionDate": "2025-01-01",
    "daysWaiting": 17,
    "program": "Dakshya",
    "mode": "Online",
    "category": "Working",
    "performance": "Excellent",
    "activityStatus": "Inactive",
    "inactiveDays": 15,
    "contactNo": "9876524073"
  },
  {
    "id": "211",
    "regId": "45955070",
    "name": "Pooja Mishra",
    "email": "pooja.mishra211@example.com",
    "batch": "March 2026",
    "admissionDate": "2025-01-01",
    "daysWaiting": 0,
    "program": "Dakshya",
    "mode": "Offline",
    "category": "Full time",
    "performance": "Very Good",
    "activityStatus": "Inactive",
    "inactiveDays": 28,
    "contactNo": "9876581107",
    "assignedMentor": "Kavita Rao"
  }
];

export const MENTORS: Mentor[] = [
  {
    "id": "1",
    "name": "Arjun Mehta",
    "email": "arjun@visionias.in",
    "currentLoad": 45,
    "capacity": 60,
    "status": "Available",
    "department": "General Studies",
    "allocatedPrograms": [
      "Foundation Course",
      "Lakshya"
    ]
  },
  {
    "id": "2",
    "name": "Kavita Rao",
    "email": "kavita@visionias.in",
    "currentLoad": 58,
    "capacity": 60,
    "status": "Near Limit",
    "department": "Optional(Geography)",
    "allocatedPrograms": [
      "Foundation Course"
    ]
  },
  {
    "id": "3",
    "name": "Sanjay Dutt",
    "email": "sanjay@visionias.in",
    "currentLoad": 60,
    "capacity": 60,
    "status": "Full",
    "department": "General Studies",
    "allocatedPrograms": [
      "Dakshya"
    ]
  },
  {
    "id": "4",
    "name": "Meera Reddy",
    "email": "meera@visionias.in",
    "currentLoad": 20,
    "capacity": 50,
    "status": "Available",
    "department": "Optional(Sociology)",
    "allocatedPrograms": [
      "Lakshya",
      "Dakshya"
    ]
  },
  {
    "id": "5",
    "name": "Rajesh Koothrappali",
    "email": "rajesh@visionias.in",
    "currentLoad": 55,
    "capacity": 60,
    "status": "Near Limit",
    "department": "Optional(PSIR)",
    "allocatedPrograms": [
      "Foundation Course"
    ]
  },
  {
    "id": "6",
    "name": "Priya Sharma",
    "email": "priya@visionias.in",
    "currentLoad": 10,
    "capacity": 50,
    "status": "Available",
    "department": "Optional(History)",
    "allocatedPrograms": [
      "Foundation Course"
    ]
  },
  {
    "id": "7",
    "name": "Amit Patel",
    "email": "amit@visionias.in",
    "currentLoad": 25,
    "capacity": 40,
    "status": "Available",
    "department": "Optional(Anthropology)",
    "allocatedPrograms": [
      "Lakshya"
    ]
  },
  {
    "id": "8",
    "name": "Vikram Singh",
    "email": "vikram@visionias.in",
    "currentLoad": 5,
    "capacity": 60,
    "status": "Available",
    "department": "General Studies",
    "allocatedPrograms": [
      "Dakshya",
      "Foundation Course"
    ]
  },
  {
    "id": "9",
    "name": "Neha Gupta",
    "email": "neha@visionias.in",
    "currentLoad": 48,
    "capacity": 50,
    "status": "Near Limit",
    "department": "Optional(History)",
    "allocatedPrograms": [
      "Foundation Course",
      "Lakshya"
    ]
  },
  {
    "id": "10",
    "name": "Rohan Das",
    "email": "rohan@visionias.in",
    "currentLoad": 30,
    "capacity": 60,
    "status": "Available",
    "department": "Optional(Sociology)",
    "allocatedPrograms": [
      "Dakshya"
    ]
  },
  {
    "id": "11",
    "name": "Anjali Menon",
    "email": "anjali@visionias.in",
    "currentLoad": 15,
    "capacity": 45,
    "status": "Available",
    "department": "Optional(PSIR)",
    "allocatedPrograms": [
      "Foundation Course"
    ]
  },
  {
    "id": "12",
    "name": "Suresh Raina",
    "email": "suresh@visionias.in",
    "currentLoad": 59,
    "capacity": 60,
    "status": "Full",
    "department": "Optional(Anthropology)",
    "allocatedPrograms": [
      "Lakshya"
    ]
  },
  {
    "id": "13",
    "name": "Pooja Hegde",
    "email": "pooja@visionias.in",
    "currentLoad": 40,
    "capacity": 60,
    "status": "Available",
    "department": "General Studies",
    "allocatedPrograms": [
      "Foundation Course",
      "Dakshya"
    ]
  },
  {
    "id": "14",
    "name": "Manoj Bajpayee",
    "email": "manoj@visionias.in",
    "currentLoad": 22,
    "capacity": 50,
    "status": "Available",
    "department": "General Studies",
    "allocatedPrograms": [
      "Lakshya"
    ]
  },
  {
    "id": "15",
    "name": "Deepika Verma",
    "email": "deepika@visionias.in",
    "currentLoad": 50,
    "capacity": 50,
    "status": "Full",
    "department": "Optional(Geography)",
    "allocatedPrograms": [
      "Foundation Course",
      "Dakshya"
    ]
  }
];

export const AUDIT_LOGS: AuditLog[] = [
  {
    "id": "1",
    "action": "Manual Assignment",
    "studentName": "Rahul Verma",
    "mentorName": "Arjun Mehta",
    "timestamp": "2024-10-24 10:30 AM",
    "details": "Assigned via fast-track"
  },
  {
    "id": "2",
    "action": "Reassignment",
    "studentName": "Sneha Gupta",
    "mentorName": "Kavita Rao",
    "timestamp": "2024-10-23 02:15 PM",
    "details": "Student request"
  },
  {
    "id": "3",
    "action": "Bulk Assignment",
    "studentName": "Batch RB01_2026",
    "mentorName": "System",
    "timestamp": "2024-10-22 09:00 AM",
    "details": "Automated batch allocation"
  }
];
